// Regenerates src/abis/ from the forge artifacts in solidity/out.
//
// Run `forge build` in solidity/ first; this script only reads what forge
// wrote. The full ABI of each contract — functions, events and errors — is
// emitted `as const satisfies Abi`, so viem infers argument and return types
// from it and a wrong call fails to compile rather than revert.
//
// The output is committed. `node scripts/codegen.mjs --check` regenerates to a
// temporary directory and diffs, so CI catches an artifact the committed copy
// has drifted from.

import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = resolve(packageDir, '..', '..', '..')
const outDir = join(repoRoot, 'solidity', 'out')
const abisDir = join(packageDir, 'src', 'abis')

// Every contract the package ships an ABI for. `file` is the source unit under
// solidity/out, `name` the contract inside it, `exportName` what a consumer
// imports. IBank exports as `bankAbi`: it is the facade the whole diamond
// answers to, and the facet ABIs exist for anyone wiring cuts by hand.
const contracts = [
  { file: 'Registry.sol', name: 'Registry', exportName: 'registryAbi' },
  { file: 'Notary.sol', name: 'Notary', exportName: 'notaryAbi' },
  { file: 'WalletFactory.sol', name: 'WalletFactory', exportName: 'walletFactoryAbi' },
  { file: 'WebWallet.sol', name: 'WebWallet', exportName: 'webWalletAbi' },
  { file: 'IBank.sol', name: 'IBank', exportName: 'bankAbi' },
  { file: 'AdminFacet.sol', name: 'AdminFacet', exportName: 'adminFacetAbi' },
  { file: 'VaultFacet.sol', name: 'VaultFacet', exportName: 'vaultFacetAbi' },
  { file: 'TransferFacet.sol', name: 'TransferFacet', exportName: 'transferFacetAbi' },
  { file: 'DiamondLoupeFacet.sol', name: 'DiamondLoupeFacet', exportName: 'diamondLoupeFacetAbi' },
  { file: 'IdentityNames.sol', name: 'IdentityNames', exportName: 'identityNamesAbi' },
  {
    file: 'GitHubIdentityVerifier.sol',
    name: 'GitHubIdentityVerifier',
    exportName: 'gitHubIdentityVerifierAbi',
  },
  {
    file: 'GoogleIdentityVerifier.sol',
    name: 'GoogleIdentityVerifier',
    exportName: 'googleIdentityVerifierAbi',
  },
  { file: 'XIdentityVerifier.sol', name: 'XIdentityVerifier', exportName: 'xIdentityVerifierAbi' },
  { file: 'IdentityJwksRoots.sol', name: 'IdentityJwksRoots', exportName: 'identityJwksRootsAbi' },
  { file: 'XZkVerifier.sol', name: 'XZkVerifier', exportName: 'xZkVerifierAbi' },
  {
    file: 'GoogleOidcVerifier.sol',
    name: 'GoogleOidcVerifier',
    exportName: 'googleOidcVerifierAbi',
  },
  { file: 'MockERC20.sol', name: 'MockERC20', exportName: 'mockErc20Abi' },
  { file: 'WTIA9.sol', name: 'WTIA9', exportName: 'wtia9Abi' },
]

const banner = (source) =>
  `// Generated by ts/packages/contracts/scripts/codegen.mjs. Do not edit.\n// Source artifact: solidity/out/${source}\n`

// The forge artifact carries `internalType` alongside `type`. It is kept:
// viem ignores it, and it is what tells a human (and abitype's docs pathways)
// which struct a tuple was.
function generate(targetDir) {
  mkdirSync(targetDir, { recursive: true })
  const moduleNames = []

  for (const { file, name, exportName } of contracts) {
    const artifactPath = join(outDir, file, `${name}.json`)
    let artifact
    try {
      artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
    } catch (err) {
      console.error(`ERROR: cannot read ${artifactPath} — run \`forge build\` in solidity/ first`)
      throw err
    }

    const moduleName = exportName.replace(/Abi$/, '')
    moduleNames.push({ moduleName, exportName })

    const body = JSON.stringify(artifact.abi, null, 2)
    const content = `${banner(`${file}/${name}.json`)}
import type { Abi } from 'viem'

export const ${exportName} = ${body} as const satisfies Abi
`
    writeFileSync(join(targetDir, `${moduleName}.ts`), content)
  }

  const index = `${banner('*')}${moduleNames
    .map(({ moduleName, exportName }) => `export { ${exportName} } from './${moduleName}.js'`)
    .join('\n')}\n`
  writeFileSync(join(targetDir, 'index.ts'), index)
}

const check = process.argv.includes('--check')

if (!check) {
  rmSync(abisDir, { recursive: true, force: true })
  generate(abisDir)
  console.log(`wrote ${contracts.length + 1} files to src/abis/`)
} else {
  const tempDir = mkdtempSync(join(tmpdir(), 'libid-abis-'))
  try {
    generate(tempDir)
    try {
      execFileSync('diff', ['-ru', abisDir, tempDir], { stdio: 'inherit' })
    } catch {
      console.error(
        'ERROR: src/abis/ is out of date with solidity/out. Run `pnpm codegen` and commit.',
      )
      process.exit(1)
    }
    console.log('src/abis/ matches the forge artifacts')
  } finally {
    rmSync(tempDir, { recursive: true, force: true })
  }
}
