// Regenerates src/abis/ and src/calls/ from the forge artifacts in
// solidity/out.
//
// src/abis/ carries the ABI of each contract. src/calls/ carries one call
// builder per state-changing function, so a caller names the function instead
// of assembling `encodeFunctionData` by hand, and adding a write to a contract
// produces its wrapper rather than requiring someone to remember to write one.
//
// Run `forge build` in solidity/ first; this script only reads what forge
// wrote. The full ABI of each contract — functions, events and errors — is
// emitted `as const satisfies Abi`, so viem infers argument and return types
// from it and a wrong call fails to compile rather than revert.
//
// The output is NOT committed: src/abis/ is gitignored and regenerated on
// demand. Run this before `pnpm build` — tsc compiles src/abis into dist and
// the package ships both. CI runs it in every job that builds the package,
// publishing included.

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = resolve(packageDir, '..', '..', '..')
const outDir = join(repoRoot, 'solidity', 'out')
const abisDir = join(packageDir, 'src', 'abis')
const callsDir = join(packageDir, 'src', 'calls')

// Every contract the package ships an ABI for. `file` is the source unit under
// solidity/out, `name` the contract inside it, `exportName` what a consumer
// imports.
const contracts = [
  { file: 'IdentityRegistry.sol', name: 'IdentityRegistry', exportName: 'identityRegistryAbi' },
  { file: 'HandleResolver.sol', name: 'HandleResolver', exportName: 'handleResolverAbi' },
  { file: 'HandleEscrow.sol', name: 'HandleEscrow', exportName: 'handleEscrowAbi' },
  { file: 'NotaryService.sol', name: 'NotaryService', exportName: 'notaryServiceAbi' },
  {
    file: 'CeremonyProofVerifier.sol',
    name: 'CeremonyProofVerifier',
    exportName: 'ceremonyProofVerifierAbi',
  },
  { file: 'GoogleJwtRoots.sol', name: 'GoogleJwtRoots', exportName: 'googleJwtRootsAbi' },
  // No contract implements it: its two functions take the payload structs the
  // Platform Verifiers decode, so their tuple types reach an ABI.
  // `src/payloads.ts` encodes against it.
  {
    file: 'ICeremonyPayloads.sol',
    name: 'ICeremonyPayloads',
    exportName: 'ceremonyPayloadsAbi',
  },
  { file: 'LibidFactory.sol', name: 'LibidFactory', exportName: 'libidFactoryAbi' },
  { file: 'WTIA9.sol', name: 'WTIA9', exportName: 'wtia9Abi' },
]

// Every contract a `bind` passes through, in the order the call reaches them:
// the registry, the Proof Verifier it dispatches to, the Platform Verifier the
// version routes to, and the Notary Service a notarized session is
// authenticated through. A revert from any of them comes back out of `bind`
// unchanged, so their errors together are what decodes one. `bindErrorsAbi`
// carries each once, by signature. The Honk verifiers are not on the list:
// bb's generated code reverts from assembly with selectors no ABI declares
// (`SumcheckFailed()` among them), so their artifacts carry no errors.
const bindRoute = [
  ['IdentityRegistry.sol', 'IdentityRegistry'],
  ['CeremonyProofVerifier.sol', 'CeremonyProofVerifier'],
  ['XPlatformVerifier.sol', 'XPlatformVerifier'],
  ['GitHubPlatformVerifier.sol', 'GitHubPlatformVerifier'],
  ['GooglePlatformVerifier.sol', 'GooglePlatformVerifier'],
  ['NotaryService.sol', 'NotaryService'],
]

function readArtifact(file, name) {
  const artifactPath = join(outDir, file, `${name}.json`)
  try {
    return JSON.parse(readFileSync(artifactPath, 'utf8'))
  } catch (err) {
    console.error(`ERROR: cannot read ${artifactPath} — run \`forge build\` in solidity/ first`)
    throw err
  }
}

/// The errors of every contract on the bind route, each signature once.
function bindErrors() {
  const bySignature = new Map()
  for (const [file, name] of bindRoute) {
    for (const entry of readArtifact(file, name).abi) {
      if (entry.type !== 'error') continue
      const signature = `${entry.name}(${entry.inputs.map((i) => i.type).join(',')})`
      if (!bySignature.has(signature)) bySignature.set(signature, entry)
    }
  }
  return [...bySignature.values()]
}

const banner = (source) =>
  `// Generated by ts/packages/contracts/scripts/codegen.mjs. Do not edit.\n// Source artifact: solidity/out/${source}\n`

// The forge artifact carries `internalType` alongside `type`. It is kept:
// viem ignores it, and it is what tells a human (and abitype's docs pathways)
// which struct a tuple was.
function generate(abisTarget, callsTarget) {
  mkdirSync(abisTarget, { recursive: true })
  mkdirSync(callsTarget, { recursive: true })
  const moduleNames = []
  const callModules = []

  for (const { file, name, exportName } of contracts) {
    const artifact = readArtifact(file, name)

    const moduleName = exportName.replace(/Abi$/, '')
    moduleNames.push({ moduleName, exportName })

    const body = JSON.stringify(artifact.abi, null, 2)
    const content = `${banner(`${file}/${name}.json`)}
import type { Abi } from 'viem'

export const ${exportName} = ${body} as const satisfies Abi
`
    writeFileSync(join(abisTarget, `${moduleName}.ts`), content)

    const calls = callModule({ file, name, exportName, moduleName, abi: artifact.abi })
    if (calls) {
      writeFileSync(join(callsTarget, `${moduleName}.ts`), calls)
      callModules.push(moduleName)
    }
  }

  const route = bindRoute.map(([file, name]) => `${file}/${name}.json`).join(', ')
  writeFileSync(
    join(abisTarget, 'bindErrors.ts'),
    `${banner(route)}
import type { Abi } from 'viem'

/// Every error a \`bind\` can revert with, from each contract on its route,
/// each signature once: what \`decodeErrorResult\` needs to name a refused bind.
export const bindErrorsAbi = ${JSON.stringify(bindErrors(), null, 2)} as const satisfies Abi
`,
  )
  moduleNames.push({ moduleName: 'bindErrors', exportName: 'bindErrorsAbi' })

  const index = `${banner('*')}${moduleNames
    .map(({ moduleName, exportName }) => `export { ${exportName} } from './${moduleName}.js'`)
    .join('\n')}\n`
  writeFileSync(join(abisTarget, 'index.ts'), index)

  // Namespaced, because names collide across contracts — `initialize` and
  // `upgradeToAndCall` are on almost every one of them. `calls.identityRegistry`
  // reads as the contract it targets.
  const callsIndex = `${banner('*')}${callModules
    .map((m) => `export * as ${m} from './${m}.js'`)
    .join('\n')}\n`
  writeFileSync(join(callsTarget, 'index.ts'), callsIndex)

  return { abis: moduleNames.length, calls: callModules.length }
}

/// One builder per state-changing function.
///
/// Arguments are not spelled out here: `ContractFunctionArgs` reads them off
/// the ABI, so there is no Solidity-to-TypeScript type table in this script to
/// drift from the real one. It resolves overloads to a union of tuples too,
/// which is what keeps one builder per name should a contract ever overload one.
///
/// Payable functions take `value` before their arguments. That is the whole
/// reason to distinguish them: a caller who forgets the value on a payable
/// write gets a revert that says nothing, and a `value` on a nonpayable one is
/// a mistake the type system should reject rather than the chain.
function callModule({ file, name, exportName, moduleName, abi }) {
  const writes = abi.filter(
    (entry) =>
      entry.type === 'function' &&
      entry.stateMutability !== 'view' &&
      entry.stateMutability !== 'pure',
  )
  if (writes.length === 0) return null

  // One builder per NAME, not per entry: viem picks the overload from the
  // arguments, so emitting both would be a duplicate declaration.
  const seen = new Map()
  for (const entry of writes) {
    if (!seen.has(entry.name)) seen.set(entry.name, entry.stateMutability === 'payable')
    // An overload set counts as payable only if every member is: otherwise
    // `value` would be required on a call that cannot accept it.
    else seen.set(entry.name, seen.get(entry.name) && entry.stateMutability === 'payable')
  }

  const Pascal = moduleName[0].toUpperCase() + moduleName.slice(1)
  const fnType = `${Pascal}Fn`
  const argsType = `${Pascal}Args`
  const builders = [...seen.entries()].map(([fn, payable]) => {
    const params = payable
      ? `to: Address, value: bigint, ...args: ${argsType}<'${fn}'>`
      : `to: Address, ...args: ${argsType}<'${fn}'>`
    const fields = payable ? 'to,\n    value,' : 'to,'
    return `export function ${fn}(${params}): Call {
  return {
    ${fields}
    data: encodeFunctionData({ abi: ${exportName}, functionName: '${fn}', args }),
  }
}`
  })

  return `${banner(`${file}/${name}.json`)}
import {
  type Address,
  type ContractFunctionArgs,
  type ContractFunctionName,
  encodeFunctionData,
} from 'viem'

import type { Call } from '../call.js'
import { ${exportName} } from '../abis/${moduleName}.js'

type Mutability = 'nonpayable' | 'payable'
type ${fnType} = ContractFunctionName<typeof ${exportName}, Mutability>
type ${argsType}<F extends ${fnType}> = ContractFunctionArgs<typeof ${exportName}, Mutability, F>

${builders.join('\n\n')}
`
}

if (process.argv.length > 2) {
  console.error(`unknown argument: ${process.argv[2]}`)
  process.exit(2)
}

rmSync(abisDir, { recursive: true, force: true })
rmSync(callsDir, { recursive: true, force: true })
const counts = generate(abisDir, callsDir)

// Formatted rather than emitted pre-wrapped: biome owns where the lines break,
// and reproducing its rules here would be a second formatter to keep in sync.
// `regen-identity-handles.py` pipes its Solidity through `forge fmt` for the
// same reason.
const biome = join(repoRoot, 'ts', 'node_modules', '.bin', 'biome')
if (!existsSync(biome)) {
  console.error(`ERROR: ${biome} not found — run \`pnpm -C ts install\` first`)
  process.exit(1)
}
// cwd is ts/, not the repo root: biome walks upward for its configuration and
// finds two roots from anywhere above it.
execFileSync(biome, ['format', '--write', abisDir, callsDir], {
  cwd: join(repoRoot, 'ts'),
  stdio: 'inherit',
})

console.log(`wrote ${counts.abis + 1} files to src/abis/, ${counts.calls + 1} to src/calls/`)
