// Generated by ts/packages/contracts/scripts/codegen.mjs. Do not edit.
// Source artifact: solidity/out/Registry.sol/Registry.json

import type { Abi } from 'viem'

export const registryAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CLOCK_SKEW_GRACE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "UPGRADE_INTERFACE_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "backend",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "contract_to_handles",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCurrentHandles",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "platforms",
        "type": "string[]",
        "internalType": "string[]"
      },
      {
        "name": "handles",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getHandles",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "platforms",
        "type": "string[]",
        "internalType": "string[]"
      },
      {
        "name": "handles",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPlatform",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "endpoint",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handlePrefix",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getUserIds",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "platforms",
        "type": "string[]",
        "internalType": "string[]"
      },
      {
        "name": "userIds",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "handleHint",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "idMeta",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "handle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "verifiedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "_notaryContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_backend",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_walletFactory",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isZkDomainSupported",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "linkIdentity",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "proof",
        "type": "tuple",
        "internalType": "struct Registry.FullTlsProof",
        "components": [
          {
            "name": "notarySignature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "backendSignature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "userAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "walletAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "domainHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "clientRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverEphemeralKey",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "transcriptRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "domainPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "usernamePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "endpointPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "idPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          }
        ]
      },
      {
        "name": "endpoint",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "link_identity_oidc",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "oidcProof",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "sessionAddr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "link_identity_zk",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "zkProof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "notary",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "notaryContract",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "oidcVerifierOf",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IOidcVerifier"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "platformConfigs",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "endpoint",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handlePrefix",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "idPrefix",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "idSuffix",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proxiableUUID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "refreshHandleHint",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "id",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "proof",
        "type": "tuple",
        "internalType": "struct Registry.FullTlsProof",
        "components": [
          {
            "name": "notarySignature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "backendSignature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "userAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "walletAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "domainHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "clientRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverEphemeralKey",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "transcriptRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "domainPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "usernamePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "endpointPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "idPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          }
        ]
      },
      {
        "name": "endpoint",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "register_session",
    "inputs": [
      {
        "name": "proof",
        "type": "tuple",
        "internalType": "struct Registry.FullTlsProof",
        "components": [
          {
            "name": "notarySignature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "backendSignature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "userAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "walletAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "domainHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "clientRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverEphemeralKey",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "transcriptRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "domainPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "usernamePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "endpointPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "idPath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          }
        ]
      },
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "username",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "endpoint",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "register_session_oidc",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "oidcProof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "register_session_zk",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "zkProof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removePlatform",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resolve",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolveById",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "id",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setBackend",
    "inputs": [
      {
        "name": "_backend",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOidcVerifier",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "verifier",
        "type": "address",
        "internalType": "contract IOidcVerifier"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPlatform",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "endpoint",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "handlePrefix",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "idPrefix",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "idSuffix",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setZkVerifier",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "verifier",
        "type": "address",
        "internalType": "contract IZkSessionVerifier"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unpause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "upgradeToAndCall",
    "inputs": [
      {
        "name": "newImplementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "usedBearerNullifiers",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "usedSessionKeys",
    "inputs": [
      {
        "name": "sessionAddr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "walletFactory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract WalletFactory"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "walletOf",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "zkVerifierOf",
    "inputs": [
      {
        "name": "domain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IZkSessionVerifier"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "HandleChanged",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "userId",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HandleRegistered",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "IdentityLinked",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "wallet",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SessionRegistered",
    "inputs": [
      {
        "name": "platform",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "handle",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "wallet",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sessionAddr",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Upgraded",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BearerNullifierUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignatureLength",
    "inputs": [
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignatureS",
    "inputs": [
      {
        "name": "s",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967InvalidImplementation",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967NonPayable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpectedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FailedCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FutureProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IdentityAlreadyLinked",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBackendSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMerkleProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNotarySignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JwtExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LinkWalletMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MerklePathTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotRegisteredWallet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OidcVerifierNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ProofExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionKeyAlreadyUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StaleProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnauthorizedCallContext",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnsupportedProxiableUUID",
    "inputs": [
      {
        "name": "slot",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedPlatform",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UserIdRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongEndpoint",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongWalletAddr",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZkVerifierNotSet",
    "inputs": []
  }
] as const satisfies Abi
