// Generated by ts/packages/contracts/scripts/codegen.mjs. Do not edit.
// Source artifact: solidity/out/TransferFacet.sol/TransferFacet.json

import type { Abi } from 'viem'

export const transferFacetAbi = [
  {
    "type": "function",
    "name": "transfer_within",
    "inputs": [
      {
        "name": "receiverPlatform",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "receiverHandle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "receiverUserId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "verifyProof",
    "inputs": [
      {
        "name": "resource",
        "type": "tuple",
        "internalType": "struct ResourceInfo",
        "components": [
          {
            "name": "platform",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "resourceType",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "resourceId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "requestPath",
            "type": "string",
            "internalType": "string"
          }
        ]
      },
      {
        "name": "sender",
        "type": "tuple",
        "internalType": "struct SenderInfo",
        "components": [
          {
            "name": "author",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "revealedAuthor",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "revealedAuthorId",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "revealedSubsection",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "notaryTlsProof",
        "type": "tuple",
        "internalType": "struct NotaryTlsProof",
        "components": [
          {
            "name": "notarySig",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "domainHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "clientRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverEphemeralKey",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "transcriptRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bodyMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "authorMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "domainMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "endpointMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "authorIdMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "receiverIdMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedReceiverId",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "quotedRefMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedQuotedRef",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "quotedAuthorMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedQuotedAuthorId",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "backendSigData",
        "type": "tuple",
        "internalType": "struct BackendSig",
        "components": [
          {
            "name": "sig",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "receiverUserId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "webTransferV2",
    "inputs": [
      {
        "name": "resource",
        "type": "tuple",
        "internalType": "struct ResourceInfo",
        "components": [
          {
            "name": "platform",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "resourceType",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "resourceId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "requestPath",
            "type": "string",
            "internalType": "string"
          }
        ]
      },
      {
        "name": "sender",
        "type": "tuple",
        "internalType": "struct SenderInfo",
        "components": [
          {
            "name": "author",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "revealedAuthor",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "revealedAuthorId",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "revealedSubsection",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "notaryTlsProof",
        "type": "tuple",
        "internalType": "struct NotaryTlsProof",
        "components": [
          {
            "name": "notarySig",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "domainHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "clientRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverEphemeralKey",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "transcriptRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bodyMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "authorMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "domainMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "endpointMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "authorIdMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "receiverIdMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedReceiverId",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "quotedRefMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedQuotedRef",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "quotedAuthorMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedQuotedAuthorId",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "backendSigData",
        "type": "tuple",
        "internalType": "struct BackendSig",
        "components": [
          {
            "name": "sig",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "receiverHandle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "receiverUserId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "tokenName_",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "amountStr",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sourceUrl",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "webTransferV2",
    "inputs": [
      {
        "name": "resource",
        "type": "tuple",
        "internalType": "struct ResourceInfo",
        "components": [
          {
            "name": "platform",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "resourceType",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "resourceId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "requestPath",
            "type": "string",
            "internalType": "string"
          }
        ]
      },
      {
        "name": "sender",
        "type": "tuple",
        "internalType": "struct SenderInfo",
        "components": [
          {
            "name": "author",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "revealedAuthor",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "revealedAuthorId",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "revealedSubsection",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "notaryTlsProof",
        "type": "tuple",
        "internalType": "struct NotaryTlsProof",
        "components": [
          {
            "name": "notarySig",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "domainHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "clientRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverRandom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "serverEphemeralKey",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "transcriptRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bodyMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "authorMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "domainMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "endpointMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "authorIdMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "receiverIdMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedReceiverId",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "quotedRefMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedQuotedRef",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "quotedAuthorMerklePath",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "revealedQuotedAuthorId",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "backendSigData",
        "type": "tuple",
        "internalType": "struct BackendSig",
        "components": [
          {
            "name": "sig",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "receiverHandle",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "receiverUserId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountStr",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sourceUrl",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "TransferWithin",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "receiverPlatform",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "receiverHandle",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "receiverUserId",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WebTransferV3",
    "inputs": [
      {
        "name": "senderWallet",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "receiverWallet",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "receiverPlatform",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "receiverHandle",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "receiverUserId",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "sourceUrl",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AmountWeiMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AuthorNotInRevealedField",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DomainHashMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignatureLength",
    "inputs": [
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignatureS",
    "inputs": [
      {
        "name": "s",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyAuthorId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyQuotedValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAllowance",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBackendSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMerkleProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNotarySignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRange",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MalformedAuthorId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MerklePathTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MultipleDecimalPoints",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoTemplateMatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedAuthorDifferentObject",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedAuthorLeafNotIncludes",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedAuthorLeafTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedAuthorMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedAuthorMissingAuthorId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedAuthorMissingQuotedId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedRefMissingId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedRefNotFlatObject",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedRefNotObject",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuotedRefTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RecipientLessNeedsReplyTarget",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RefNotQuote",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReplyLeafNotInReplyTo",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReplyLeafTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReplyTargetIdNotQuoted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReplyTargetMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RequestPathMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SenderNotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SourceUrlDomainMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SourceUrlNotHttps",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StringsInsufficientHexLength",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TemplateNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TokenNotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferAlreadyUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownResourceType",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UserIdRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroToken",
    "inputs": []
  }
] as const satisfies Abi
