// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by scripts/vendor-circuit-verifiers.sh from a local libid-circuits build of commit d5b0523a3712f64e72fc9e774b22fa3427949074 (unreleased, unpinned). Do not edit.

/// @notice The runtime code hash of each circuit's vendored Honk verifier: what
///         EXTCODEHASH reports at any deployed copy. A Platform Verifier pins
///         its own circuit's and refuses every other verifier.
library CircuitCodehashes {
    /// `BearerLinkGithubHonkVerifier`, the `bearer-link-github` circuit's verifier.
    bytes32 internal constant BEARER_LINK_GITHUB = 0x64d3313bd608366f81b41441d841b376693360f1504704fc16e623f97e24861e;
    /// `BearerLinkXHonkVerifier`, the `bearer-link-x` circuit's verifier.
    bytes32 internal constant BEARER_LINK_X = 0x5b74624c27ab6b7e43e5edaa442c008727290ccae08b76f2fcdf5bba059863f1;
    /// `OidcGoogleHonkVerifier`, the `oidc-google` circuit's verifier.
    bytes32 internal constant OIDC_GOOGLE = 0xd3a0c4569d0a3a5d13056ce0124c4c1bf6fc2c85e4654411903c1007287f8eed;
}
