// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by scripts/vendor-circuit-verifiers.sh from a local libid-circuits build of commit 487cbab2427e66a02034e94843bad249b17574c2 (unreleased, unpinned). Do not edit.

/// @notice The runtime code hash of each circuit's vendored Honk verifier: what
///         EXTCODEHASH reports at any deployed copy. A Platform Verifier pins
///         its own circuit's and refuses every other verifier.
library CircuitCodehashes {
    /// `BearerLinkGithubHonkVerifier`, the `bearer-link-github` circuit's verifier.
    bytes32 internal constant BEARER_LINK_GITHUB = 0x08058f64a0c1ae171644ed09978cedc1a56394c6b26570891ba151be630bfcc9;
    /// `BearerLinkXHonkVerifier`, the `bearer-link-x` circuit's verifier.
    bytes32 internal constant BEARER_LINK_X = 0xb9197b1a95ace9f53fff302b3cf25da65c54e620fda84fef5289a80624fec309;
    /// `OidcGoogleHonkVerifier`, the `oidc-google` circuit's verifier.
    bytes32 internal constant OIDC_GOOGLE = 0x0885c2107d0c775b98860bdbd886059d94d964e940363f01ae1084c876ae7340;
}
