// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by scripts/regen-ceremony-profiles.py. Do not edit.
// The source of truth is solidity/contracts/ceremony/profiles.json.

/// @title CeremonyProfile
/// @notice The tags a Platform Verifier pins, and the governance-owned
///         protocol parameters it reads.
///
/// The single source of truth for the ceremony profiles. Solidity, Rust and
/// TypeScript constants are generated from this file by
/// scripts/regen-ceremony-profiles.py. The Platform Verifiers are hand
/// written and READ these constants; only the values live here.
///
/// THESE STRINGS ARE OURS, NOT THE SPECIFICATION'S. ceremony-common fixes no
/// literal of its own: platform-ceremonies REQ-PLAT-01 fixes the profile
/// NAMES, and every byte below is the profile author's choice. So this is a
/// cross-implementation agreement, and it is agreed here rather than four
/// times over.
///
/// Four components must produce the same bytes: this repository's verifiers,
/// the browser that notarizes three of the four sessions, the deployment that
/// notarizes the fourth, and the notary that signs what they observed. A
/// disagreement is silent -- a Consumer dispatching on one string and a
/// verifier registered under another simply never meet, and a request line a
/// prover composes one byte differently is an attestation rejected with no
/// error that says why.
///
/// Changing a value here changes what a deployed verifier accepts. That is a
/// new ceremonyVersion, not an edit.
library CeremonyProfile {
    // --- Platform identifiers -----------------------------------------------

    bytes32 internal constant PLATFORM_GOOGLE = keccak256(bytes("google"));
    bytes32 internal constant PLATFORM_X = keccak256(bytes("x"));
    bytes32 internal constant PLATFORM_GITHUB = keccak256(bytes("github"));

    // --- Authorities --------------------------------------------------------

    /// @dev The lowercase ASCII TLS server name, with no trailing dot, that the
    ///      notary authenticated. It reaches the verifier as `authorityId` and
    ///      never as a transcript range: the transcript holds the authority
    ///      only in a prover-composed `Host` header, which says nothing about
    ///      which server answered (REQ-COMMON-21, REQ-COMMON-21A).

    bytes32 internal constant AUTHORITY_X_API = keccak256(bytes("api.x.com"));
    bytes32 internal constant AUTHORITY_GITHUB = keccak256(bytes("github.com"));
    bytes32 internal constant AUTHORITY_GITHUB_API = keccak256(bytes("api.github.com"));

    // --- Sessions -------------------------------------------------------------

    /// @dev The request-line prefix each session sends, trailing space included.
    ///      The space is load-bearing: without it `GET /user ` would prefix
    ///      `GET /users/me`, and one profile's path would answer for another's.

    bytes internal constant X_TOKEN_REQUEST_LINE = "POST /2/oauth2/token ";
    bytes internal constant X_IDENTITY_REQUEST_LINE = "GET /2/users/me ";
    bytes internal constant GITHUB_TOKEN_REQUEST_LINE = "POST /login/oauth/access_token ";
    bytes internal constant GITHUB_IDENTITY_REQUEST_LINE = "GET /user ";

    /// @dev The lines a verifier requires of the token request's head, each
    ///      exactly once with its value: `host` naming the pinned authority,
    ///      and the media type that selects the platform's request parser
    ///      (REQ-COMMON-21B). Revealed but uncompared, the media type was a
    ///      byte a prover chose in a request every other field of which is
    ///      pinned. What else a runtime sends is its own and not stated here.

    bytes internal constant X_TOKEN_REQUIRED_HEADERS =
        "host: api.x.com\r\ncontent-type: application/x-www-form-urlencoded";
    bytes internal constant GITHUB_TOKEN_REQUIRED_HEADERS =
        "host: github.com\r\ncontent-type: application/x-www-form-urlencoded";

    /// @dev Header names a token request must not carry, compared lowercased by
    ///      every Platform Verifier. Each changes what the platform does with the
    ///      request in a way no revealed byte shows: `authorization` which client
    ///      it authenticates, `content-encoding` and `transfer-encoding` which
    ///      bytes it parses, `cookie` the context, `x-http-method-override` the
    ///      method. The verifier requires each token session's requiredHeaders,
    ///      `host` and `content-type`, reads `content-length`, and ignores every
    ///      other header: one outside both lists changes only what the platform
    ///      answers, and a wrong answer is a response the verifier cannot read.
    bytes internal constant FORBIDDEN_TOKEN_REQUEST_HEADERS =
        "authorization\r\ncontent-encoding\r\ncookie\r\ntransfer-encoding\r\nx-http-method-override";

    /// @dev How many committed ranges the token request carries. A confidential
    ///      client commits its secret and a public client hides nothing, so this
    ///      is one or zero and never a preference.

    uint256 internal constant X_TOKEN_SENT_COMMITMENTS = 0;
    uint256 internal constant GITHUB_TOKEN_SENT_COMMITMENTS = 1;

    /// @dev The two identity members a Platform Verifier reads out of the
    ///      revealed response bytes (REQ-PLAT-51).

    string internal constant X_ID_FIELD = "id";
    string internal constant X_HANDLE_FIELD = "username";
    string internal constant GITHUB_ID_FIELD = "id";
    string internal constant GITHUB_HANDLE_FIELD = "login";

    // --- Launch profile shape ------------------------------------------------

    /// @dev Launch profiles are `google/v1`, `x/v1`, `github/v1`
    ///      (REQ-PLAT-01).
    uint16 internal constant LAUNCH_VERSION = 1;

    /// @dev Derived from the session list each profile fixes, never stated
    ///      beside it (REQ-COMMON-41).
    function attestationCount(bytes32 platformId) internal pure returns (uint8) {
        if (platformId == PLATFORM_GOOGLE) return 0;
        if (platformId == PLATFORM_X || platformId == PLATFORM_GITHUB) return 2;
        revert UnknownPlatform(platformId);
    }

    error UnknownPlatform(bytes32 platformId);

    // --- Protocol parameters -------------------------------------------------

    /// @dev Governance-owned seconds, read where they are enforced. A Platform
    ///      Verifier reads the current value when it verifies and MUST NOT accept a
    ///      caller-supplied substitute (REQ-PARAM-02). These are the launch values;
    ///      a deployment stores and updates them.
    uint64 internal constant LAUNCH_PROOF_LIFETIME_X = 3600;
    uint64 internal constant LAUNCH_PROOF_LIFETIME_GITHUB = 3600;
    uint64 internal constant LAUNCH_MAX_FUTURE_ATTESTATION_SKEW = 300;
}
