// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by scripts/regen-ceremony-profiles.py. Do not edit.
// The source of truth is solidity/contracts/ceremony/profiles.json.

/// @title CeremonyProfile
/// @notice The tags a Platform Verifier pins, and the validity window
///         each profile fixes.
///
/// The single source of truth for the ceremony profiles. Solidity, Rust and
/// TypeScript constants are generated from this file by
/// scripts/regen-ceremony-profiles.py. The Platform Verifiers are hand
/// written and READ these constants; only the values live here.
///
/// THESE STRINGS ARE OURS, NOT THE SPECIFICATION'S. ceremony-common fixes no
/// literal of its own: platform-ceremonies REQ-PLAT-01 fixes the profile
/// NAMES, and every byte below is the profile author's choice. So this is a
/// cross-implementation agreement, and it is agreed here rather than three
/// times over.
///
/// Three components must produce the same bytes: this repository's verifiers,
/// the browser that notarizes all four sessions, and the notary that signs
/// what it observed. A disagreement is silent -- a Consumer dispatching on one
/// string and a verifier registered under another simply never meet, and a
/// request line a prover composes one byte differently is an attestation
/// rejected with no error that says why.
///
/// Changing a value here changes what a deployed verifier accepts. That is a
/// new ceremonyVersion, not an edit.
library CeremonyProfile {
    // --- Platform identifiers -----------------------------------------------

    bytes32 internal constant PLATFORM_GOOGLE = keccak256(bytes("google"));
    bytes32 internal constant PLATFORM_X = keccak256(bytes("x"));
    bytes32 internal constant PLATFORM_GITHUB = keccak256(bytes("github"));

    // --- Authorities --------------------------------------------------------

    /// @dev The lowercase ASCII TLS server name, with no trailing dot, that the
    ///      notary authenticated. It reaches the verifier as `authorityId` and
    ///      never as a transcript range: the transcript holds the authority
    ///      only in a prover-composed `Host` header, which says nothing about
    ///      which server answered (REQ-COMMON-21, REQ-COMMON-21A).

    bytes32 internal constant AUTHORITY_X_API = keccak256(bytes("api.x.com"));
    bytes32 internal constant AUTHORITY_GITHUB = keccak256(bytes("github.com"));
    bytes32 internal constant AUTHORITY_GITHUB_API = keccak256(bytes("api.github.com"));

    // --- Sessions -------------------------------------------------------------

    /// @dev The request-line prefix each session sends, trailing space included.
    ///      The space is load-bearing: without it `GET /user ` would prefix
    ///      `GET /users/me`, and one profile's path would answer for another's.

    bytes internal constant X_TOKEN_REQUEST_LINE = "POST /2/oauth2/token ";
    bytes internal constant X_IDENTITY_REQUEST_LINE = "GET /2/users/me ";
    bytes internal constant GITHUB_TOKEN_REQUEST_LINE = "POST /login/oauth/access_token ";
    bytes internal constant GITHUB_IDENTITY_REQUEST_LINE = "GET /user ";

    /// @dev The lines a verifier requires of the token request's head, each
    ///      exactly once with its value: `host` naming the pinned authority,
    ///      and the media type that selects the platform's request parser
    ///      (REQ-COMMON-21B). Revealed but uncompared, the media type was a
    ///      byte a prover chose in a request every other field of which is
    ///      pinned. What else a runtime sends is its own and not stated here.

    bytes internal constant X_TOKEN_REQUIRED_HEADERS =
        "host: api.x.com\r\ncontent-type: application/x-www-form-urlencoded";
    bytes internal constant GITHUB_TOKEN_REQUIRED_HEADERS =
        "host: github.com\r\ncontent-type: application/x-www-form-urlencoded";

    /// @dev The form fields each token request's body carries, in the order
    ///      the prover serializes them, joined by `&`. Every verifier holds
    ///      the whole body to its list (`requireExactForm`): exactly these
    ///      names in this order, each once with a nonempty value and nothing
    ///      after the last. GitHub's list is REQ-PLAT-61's and X's is
    ///      REQ-PLAT-63's.

    bytes internal constant X_TOKEN_FIELDS = "grant_type&client_id&code&redirect_uri&code_verifier";
    bytes internal constant GITHUB_TOKEN_FIELDS = "client_id&code&redirect_uri&code_verifier&client_secret";

    /// @dev Header names no notarized request may carry, compared by every
    ///      Platform Verifier with the name lowercased, its whitespace removed and
    ///      `_` read as `-`. Each changes what the platform does with the request
    ///      in a way no revealed byte shows: `authorization` which client it
    ///      authenticates, `content-encoding` and `transfer-encoding` which bytes
    ///      it parses, `cookie` which session it answers for, the three override
    ///      names which method it runs. The identity request is excepted from
    ///      `authorization` alone: its one such header, under any scheme, is what
    ///      REQ-COMMON-39 counts. On the token request the verifier further
    ///      requires each session's requiredHeaders, `host` and `content-type`,
    ///      reads `content-length`, and ignores every other header: one outside
    ///      both lists changes only what the platform answers, and a wrong answer
    ///      is a response the verifier cannot read.
    bytes internal constant FORBIDDEN_REQUEST_HEADERS =
        "authorization\r\ncontent-encoding\r\ncookie\r\ntransfer-encoding\r\nx-http-method\r\nx-http-method-override\r\nx-method-override";

    /// @dev Whether `nameHash` is the keccak256 of a name
    ///      `FORBIDDEN_REQUEST_HEADERS` lists.
    function isForbiddenRequestHeader(bytes32 nameHash) internal pure returns (bool) {
        return nameHash == keccak256("authorization") || nameHash == keccak256("content-encoding")
            || nameHash == keccak256("cookie") || nameHash == keccak256("transfer-encoding")
            || nameHash == keccak256("x-http-method") || nameHash == keccak256("x-http-method-override")
            || nameHash == keccak256("x-method-override");
    }

    /// @dev The two identity members a Platform Verifier reads out of the
    ///      revealed response bytes (REQ-PLAT-51).

    string internal constant X_ID_FIELD = "id";
    string internal constant X_HANDLE_FIELD = "username";
    string internal constant GITHUB_ID_FIELD = "id";
    string internal constant GITHUB_HANDLE_FIELD = "login";

    // --- Validity -------------------------------------------------------------

    /// @dev The seconds each profile fixes. A Platform Verifier reads them as
    ///      constants: they belong to the profile like its request lines, an upgrade
    ///      of the verifier keeps them, and a different value is a new
    ///      ceremonyVersion (REQ-PARAM-01). A browser that knows the version it ran
    ///      therefore knows the validity every chain enforces. `IdentityRegistry`
    ///      supersedes a binding only on a strictly newer `observedAt`, so an
    ///      allowance too generous lets a proof dated ahead hold a name until the
    ///      clock catches up.

    // The signed `exp` bounds validity, so the profile fixes no lifetime
    // and no attestation skew. The OIDC circuit exposes no `iat`, so the
    // observation is the token's `exp`: Google issues about an hour of
    // life, and the claim reads roughly an hour ahead of the moment it
    // describes.
    uint64 internal constant FUTURE_OBSERVATION_ALLOWANCE_SECONDS_GOOGLE = 7200;

    // The token attestation's creation time is the evidence time. A
    // notary states wall-clock time as it observes it, so the observation
    // is never ahead: five minutes covers clock skew between the notary
    // and the chain.
    uint64 internal constant PROOF_LIFETIME_SECONDS_X = 3600;
    uint64 internal constant MAX_FUTURE_ATTESTATION_SKEW_SECONDS_X = 300;
    uint64 internal constant FUTURE_OBSERVATION_ALLOWANCE_SECONDS_X = 300;

    // Same as X: notary wall-clock, five minutes for skew.
    uint64 internal constant PROOF_LIFETIME_SECONDS_GITHUB = 3600;
    uint64 internal constant MAX_FUTURE_ATTESTATION_SKEW_SECONDS_GITHUB = 300;
    uint64 internal constant FUTURE_OBSERVATION_ALLOWANCE_SECONDS_GITHUB = 300;

    // --- Launch profile shape ------------------------------------------------

    /// @dev Launch profiles are `google/v1`, `x/v1`, `github/v1`
    ///      (REQ-PLAT-01).
    uint16 internal constant LAUNCH_VERSION = 1;

    /// @dev Derived from the session list each profile fixes, never stated
    ///      beside it (REQ-COMMON-41).
    function attestationCount(bytes32 platformId) internal pure returns (uint8) {
        if (platformId == PLATFORM_GOOGLE) return 0;
        if (platformId == PLATFORM_X || platformId == PLATFORM_GITHUB) return 2;
        revert UnknownPlatform(platformId);
    }

    error UnknownPlatform(bytes32 platformId);
}
