// Generated by libID-contracts' scripts/regen-identity-handles.py. Do not edit.
// The source of truth is libID-contracts' solidity/contracts/handles/handles.json.

//! Platform ids and the shared handle vector table.

/// One case from the shared table.
pub struct Vector {
    /// Platform key, as written in the source table.
    pub platform: &'static str,
    /// The handle exactly as a caller supplied it.
    pub input: &'static str,
    /// The normalized handle, or an empty string when the case is refused.
    pub output: &'static str,
    /// Whether the transform accepts this case.
    pub accepted: bool,
    /// Which refusal the case expects, when it is refused.
    pub error_kind: u8,
    /// SHA256(handle tag || output), hex, or empty when the case is refused.
    pub handle_node: &'static str,
}

/// One id case from the shared table.
pub struct IdVector {
    /// Platform key, as written in the source table.
    pub platform: &'static str,
    /// The id exactly as the platform sent it.
    pub input: &'static str,
    /// Whether the id rules accept this case.
    pub accepted: bool,
    /// Which refusal the case expects, when it is refused.
    pub error_kind: u8,
    /// SHA256(id tag || input), hex, or empty when the case is refused.
    pub id_node: &'static str,
}

/// A platform `handles.json` names: its key, its node tags and its rules.
pub struct Platform {
    /// keccak256 of this string is the platform id.
    pub key: &'static str,
    /// An id node is SHA256 of this tag, then the id.
    pub user_id_tag: &'static str,
    /// A handle node is SHA256 of this tag, then the normalized handle.
    pub handle_tag: &'static str,
    /// What a handle may be.
    pub rules: crate::Rules,
    /// What an id may be.
    pub id_rules: crate::IdRules,
}

/// SHA-256 of the handles.json this file was generated from.
pub const TABLE_SHA256: &str = "5d4c0d0db7fbab4307f7ae93add39f99344cded07e5bc8fef662369619940029";

/// keccak256 of this string is the platform id.
pub const PLATFORM_X_KEY: &str = "x";
/// keccak256 of this string is the platform id.
pub const PLATFORM_GITHUB_KEY: &str = "github";
/// keccak256 of this string is the platform id.
pub const PLATFORM_GOOGLE_KEY: &str = "google";

/// x, as `handles.json` states it.
pub const PLATFORM_X: Platform = Platform {
    key: PLATFORM_X_KEY,
    user_id_tag: "libid.x.user-id",
    handle_tag: "libid.x.handle",
    rules: crate::Rules {
        max_length: 15,
        is_email: false,
        allow_underscore: true,
        allow_hyphen: false,
    },
    id_rules: crate::IdRules {
        max_length: 20,
        decimal: true,
        leading_zero: false,
    },
};
/// github, as `handles.json` states it.
pub const PLATFORM_GITHUB: Platform = Platform {
    key: PLATFORM_GITHUB_KEY,
    user_id_tag: "libid.github.user-id",
    handle_tag: "libid.github.handle",
    rules: crate::Rules {
        max_length: 39,
        is_email: false,
        allow_underscore: false,
        allow_hyphen: true,
    },
    id_rules: crate::IdRules {
        max_length: 20,
        decimal: true,
        leading_zero: false,
    },
};
/// google, as `handles.json` states it.
pub const PLATFORM_GOOGLE: Platform = Platform {
    key: PLATFORM_GOOGLE_KEY,
    user_id_tag: "libid.google.user-id",
    handle_tag: "libid.google.handle",
    rules: crate::Rules {
        max_length: 62,
        is_email: true,
        allow_underscore: false,
        allow_hyphen: false,
    },
    id_rules: crate::IdRules {
        max_length: 31,
        decimal: false,
        leading_zero: true,
    },
};

/// Every platform, in table order.
pub static PLATFORMS: [Platform; 3] = [PLATFORM_X, PLATFORM_GITHUB, PLATFORM_GOOGLE];

/// The platform with this key, if the table names it.
pub fn platform(key: &str) -> Option<&'static Platform> {
    PLATFORMS.iter().find(|p| p.key == key)
}

/// Nothing is left after the transform.
pub const ERROR_EMPTY: u8 = 0;
/// More bytes than the platform allows.
pub const ERROR_TOOLONG: u8 = 1;
/// A byte the platform does not allow.
pub const ERROR_BADCHARACTER: u8 = 2;
/// Allowed bytes in an arrangement the platform does not allow.
pub const ERROR_BADSHAPE: u8 = 3;

/// Every case, shared with Solidity and TypeScript.
pub const VECTORS: [Vector; 48] = [
    Vector {
        platform: "x",
        input: " @Alice_1 ",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "Alice_1",
        output: "alice_1",
        accepted: true,
        error_kind: 0,
        handle_node: "0xe09c4f5bfbbc723bc35701ea9d718a1c5edb29b1ed5bb0cb0fabb3c43d8136af",
    },
    Vector {
        platform: "x",
        input: "alice",
        output: "alice",
        accepted: true,
        error_kind: 0,
        handle_node: "0x0bed64615b5776d2567a82467d7be0e266e02803910d694a72703ee2a4cc911a",
    },
    Vector {
        platform: "x",
        input: "@a",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "A1_b2",
        output: "a1_b2",
        accepted: true,
        error_kind: 0,
        handle_node: "0x55be0847f475409cb1da1d008804b966de05bb088d2469129c142faf2ec4a678",
    },
    Vector {
        platform: "x",
        input: "a12345678901234",
        output: "a12345678901234",
        accepted: true,
        error_kind: 0,
        handle_node: "0xbd3a96fb00ea79bdb486cbaa43914f8c110c8585d419fc02e5b1536c7617af58",
    },
    Vector {
        platform: "x",
        input: "a123456789012345",
        output: "",
        accepted: false,
        error_kind: 1,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "",
        output: "",
        accepted: false,
        error_kind: 0,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "   ",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "@",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "@@alice",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "alice-1",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "ali ce",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "ali\tce",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "ali\nce",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "alic\u{e9}",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "\talice",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "alice\t",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: "\nalice",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "x",
        input: " @ alice ",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "OctoCat",
        output: "octocat",
        accepted: true,
        error_kind: 0,
        handle_node: "0x381fb9d7d3b01214e58b94202ea10f78e169adef68bcc20d40c130deca6dfe74",
    },
    Vector {
        platform: "github",
        input: "@Octo-Cat",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "octocat",
        output: "octocat",
        accepted: true,
        error_kind: 0,
        handle_node: "0x381fb9d7d3b01214e58b94202ea10f78e169adef68bcc20d40c130deca6dfe74",
    },
    Vector {
        platform: "github",
        input: " OctoCat ",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "a",
        output: "a",
        accepted: true,
        error_kind: 0,
        handle_node: "0x823c23491391b659703362484a08cfbcc8cede4ea3b5ba1753c3df7756799c70",
    },
    Vector {
        platform: "github",
        input: "o-c",
        output: "o-c",
        accepted: true,
        error_kind: 0,
        handle_node: "0xaa580baff71ac37d38e08b9b7b0dd7516ec01608457fbbee7f445a0b8f7d9fc5",
    },
    Vector {
        platform: "github",
        input: "-octocat",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "octocat-",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "octo--cat",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "octo_cat",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "-",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "",
        output: "",
        accepted: false,
        error_kind: 0,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "abcdefghijabcdefghijabcdefghijabcdefghi",
        output: "abcdefghijabcdefghijabcdefghijabcdefghi",
        accepted: true,
        error_kind: 0,
        handle_node: "0x3f7bdb081795e2934e1e949f1933b8df950a6e6026dbc70060fc3a79b693a058",
    },
    Vector {
        platform: "github",
        input: "abcdefghijabcdefghijabcdefghijabcdefghij",
        output: "",
        accepted: false,
        error_kind: 1,
        handle_node: "",
    },
    Vector {
        platform: "github",
        input: "\n",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "A.B+tag@Example.COM",
        output: "a.b+tag@example.com",
        accepted: true,
        error_kind: 0,
        handle_node: "0x40169b5cc6400158aeef2a13b73a14fc36e5e1df8595572b8fe282a269f26dd4",
    },
    Vector {
        platform: "google",
        input: "alice@example.com",
        output: "alice@example.com",
        accepted: true,
        error_kind: 0,
        handle_node: "0x41c79cba63d5bd4735ca51af1af31702918f326eb6fc1afd853d675fee3a59cc",
    },
    Vector {
        platform: "google",
        input: " Alice@Example.com ",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "@Alice@example.com",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "alice",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "@example.com",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "alice@",
        output: "",
        accepted: false,
        error_kind: 3,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "",
        output: "",
        accepted: false,
        error_kind: 0,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "ali ce@example.com",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com",
        output: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com",
        accepted: true,
        error_kind: 0,
        handle_node: "0x3dc67054a8f794285dc9496fd7c2442ef34401b5e3f6a49e7d3fd9cc6a917e97",
    },
    Vector {
        platform: "google",
        input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijk@example.com",
        output: "",
        accepted: false,
        error_kind: 1,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "a\"b@example.com",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
    Vector {
        platform: "google",
        input: "a\\b@example.com",
        output: "",
        accepted: false,
        error_kind: 2,
        handle_node: "",
    },
];

/// Every id case, shared with TypeScript and Noir.
pub const ID_VECTORS: [IdVector; 24] = [
    IdVector {
        platform: "x",
        input: "2244994945",
        accepted: true,
        error_kind: 0,
        id_node: "0x68291869976ffad2abf3e933ec9ab2623395ff8b3b9242e655e1da3ef43d4f94",
    },
    IdVector {
        platform: "x",
        input: "7",
        accepted: true,
        error_kind: 0,
        id_node: "0x5c228a76caebd7cc0148637f2344c022228820a028f1fbd0d840227da5b5fa6f",
    },
    IdVector {
        platform: "x",
        input: "0",
        accepted: true,
        error_kind: 0,
        id_node: "0xec5465b57bae1d48ebc1fe214f8209caf9804813931fd6b02b34b22f6b2ec7cd",
    },
    IdVector {
        platform: "x",
        input: "0123",
        accepted: false,
        error_kind: 3,
        id_node: "",
    },
    IdVector {
        platform: "x",
        input: "00123",
        accepted: false,
        error_kind: 3,
        id_node: "",
    },
    IdVector {
        platform: "x",
        input: "12345678901234567890",
        accepted: true,
        error_kind: 0,
        id_node: "0x46d787dc85127e79b248e3768ab657f0c543bc3ce5b97f1645c69f8432a3ec3b",
    },
    IdVector {
        platform: "x",
        input: "123456789012345678901",
        accepted: false,
        error_kind: 1,
        id_node: "",
    },
    IdVector {
        platform: "x",
        input: "",
        accepted: false,
        error_kind: 0,
        id_node: "",
    },
    IdVector {
        platform: "x",
        input: "12a4",
        accepted: false,
        error_kind: 2,
        id_node: "",
    },
    IdVector {
        platform: "x",
        input: "-1",
        accepted: false,
        error_kind: 2,
        id_node: "",
    },
    IdVector {
        platform: "github",
        input: "583231",
        accepted: true,
        error_kind: 0,
        id_node: "0x475902b27989feb395b9b0cd3156aa573a9676c13155b8e7e3ddaf3e77181847",
    },
    IdVector {
        platform: "github",
        input: "0",
        accepted: true,
        error_kind: 0,
        id_node: "0x90f128b24f42f2f5b6924ca42ac0ec9220498d50b0ce131a1cf9135bd3e017c3",
    },
    IdVector {
        platform: "github",
        input: "0583231",
        accepted: false,
        error_kind: 3,
        id_node: "",
    },
    IdVector {
        platform: "github",
        input: "18446744073709551615",
        accepted: true,
        error_kind: 0,
        id_node: "0xdaaed93a4b3862ac845bdc7e3db729492757f8c0b53c6572e6897d9ae0ff54fd",
    },
    IdVector {
        platform: "github",
        input: "",
        accepted: false,
        error_kind: 0,
        id_node: "",
    },
    IdVector {
        platform: "github",
        input: "5 8",
        accepted: false,
        error_kind: 2,
        id_node: "",
    },
    IdVector {
        platform: "google",
        input: "110169484474386276334",
        accepted: true,
        error_kind: 0,
        id_node: "0x620866cfb4d2776a32cd94d8e8b55577526af86115ebf125d4ca1ca7bf07737e",
    },
    IdVector {
        platform: "google",
        input: "a b~Z",
        accepted: true,
        error_kind: 0,
        id_node: "0xa8ad7455d3d38bcd9b94b444284182fee9766f2403e7fe283c68c4a08123be77",
    },
    IdVector {
        platform: "google",
        input: "1234567890123456789012345678901",
        accepted: true,
        error_kind: 0,
        id_node: "0xe95d993e3520fe34fd3eec014d9bbf91868c7e7e5160d95bc3eeca9dfb38329e",
    },
    IdVector {
        platform: "google",
        input: "12345678901234567890123456789012",
        accepted: false,
        error_kind: 1,
        id_node: "",
    },
    IdVector {
        platform: "google",
        input: "",
        accepted: false,
        error_kind: 0,
        id_node: "",
    },
    IdVector {
        platform: "google",
        input: "a\"b",
        accepted: false,
        error_kind: 2,
        id_node: "",
    },
    IdVector {
        platform: "google",
        input: "a\\b",
        accepted: false,
        error_kind: 2,
        id_node: "",
    },
    IdVector {
        platform: "google",
        input: "a\tb",
        accepted: false,
        error_kind: 2,
        id_node: "",
    },
];
