// Generated by scripts/regen-ceremony-profiles.py. Do not edit.
// The source of truth is solidity/contracts/ceremony/profiles.json.

/**
 * The single source of truth for the ceremony profiles. Solidity, Rust and
 * TypeScript constants are generated from this file by
 * scripts/regen-ceremony-profiles.py. The Platform Verifiers are hand
 * written and READ these constants; only the values live here.
 *
 * THESE STRINGS ARE OURS, NOT THE SPECIFICATION'S. ceremony-common fixes no
 * literal of its own: platform-ceremonies REQ-PLAT-01 fixes the profile
 * NAMES, and every byte below is the profile author's choice. So this is a
 * cross-implementation agreement, and it is agreed here rather than four
 * times over.
 *
 * Four components must produce the same bytes: this repository's verifiers,
 * the browser that notarizes three of the four sessions, the deployment that
 * notarizes the fourth, and the notary that signs what they observed. A
 * disagreement is silent -- a Consumer dispatching on one string and a
 * verifier registered under another simply never meet, and a request line a
 * prover composes one byte differently is an attestation rejected with no
 * error that says why.
 *
 * Changing a value here changes what a deployed verifier accepts. That is a
 * new ceremonyVersion, not an edit: --check compares every shipped profile
 * against the last release and refuses a changed profile that kept its
 * version. `deployed` is what says which profiles that rule has taken hold
 * of -- until one is registered somewhere, its bytes are still being agreed
 * and there is no verifier for a version bump to protect.
 */

/** Which shape a platform's immutable identifier takes in its response. */
export type IdShape = 'jsonString' | 'jsonInteger'

export interface Session {
  /** The lowercase TLS server name the notary authenticates. */
  readonly authority: string
  readonly method: string
  readonly path: string
  /** The request-line prefix the verifier compares byte for byte. */
  readonly requestLine: string
}

export interface TokenSession {
  readonly session: Session
  /** The body field committed rather than revealed, or null. */
  readonly secretField: string | null
  /** Every header this request sends, lowercased, in the order to set them.
   * `content-length` is absent: the HTTP client appends it. */
  readonly requestHeaders: readonly string[]
  /** Those headers as the run of bytes the Platform Verifier compares, ending
   * at the `content-length` value it reads out of the transcript. */
  readonly requestHeaderBlock: string
}

export interface IdentitySession {
  readonly session: Session
  readonly idField: string
  readonly idShape: IdShape
  readonly handleField: string
}

export interface Profile {
  /** The platform name. The platform id is its keccak256. */
  readonly platform: string
  readonly ceremonyVersion: number
  readonly token: TokenSession | null
  readonly identity: IdentitySession | null
}

/**
 * Google's evidence is a signed token checked against Google's published
 * keys, so the profile notarizes nothing: no session, no attestation,
 * and no Notary Fee.
 */
export const GOOGLE: Profile = {
  platform: 'google',
  ceremonyVersion: 1,
  token: null,
  identity: null,
}

/**
 * A public client with S256 PKCE and two browser-owned sessions, both
 * served by the same host.
 */
export const X: Profile = {
  platform: 'x',
  ceremonyVersion: 1,
  token: {
    session: {
      authority: 'api.x.com',
      method: 'POST',
      path: '/2/oauth2/token',
      requestLine: 'POST /2/oauth2/token ',
    },
    secretField: null,
    requestHeaders: [
      'host: api.x.com',
      'content-type: application/x-www-form-urlencoded',
      'accept: application/json',
      'connection: close',
    ],
    requestHeaderBlock:
      'host: api.x.com\r\ncontent-type: application/x-www-form-urlencoded\r\naccept: application/json\r\nconnection: close',
  },
  identity: {
    session: {
      authority: 'api.x.com',
      method: 'GET',
      path: '/2/users/me',
      requestLine: 'GET /2/users/me ',
    },
    idField: 'id',
    idShape: 'jsonString',
    handleField: 'username',
  },
}

/**
 * A confidential client. The exchange runs in the deployment because the
 * secret cannot reach the browser, and the two sessions are served by
 * DIFFERENT hosts -- which is why one pinned authority per profile would
 * be wrong.
 */
export const GITHUB: Profile = {
  platform: 'github',
  ceremonyVersion: 1,
  token: {
    session: {
      authority: 'github.com',
      method: 'POST',
      path: '/login/oauth/access_token',
      requestLine: 'POST /login/oauth/access_token ',
    },
    secretField: 'client_secret',
    requestHeaders: [
      'host: github.com',
      'content-type: application/x-www-form-urlencoded',
      'accept: application/json',
      'connection: close',
    ],
    requestHeaderBlock:
      'host: github.com\r\ncontent-type: application/x-www-form-urlencoded\r\naccept: application/json\r\nconnection: close',
  },
  identity: {
    session: {
      authority: 'api.github.com',
      method: 'GET',
      path: '/user',
      requestLine: 'GET /user ',
    },
    idField: 'id',
    idShape: 'jsonInteger',
    handleField: 'login',
  },
}

/** The closed launch list. */
export const LAUNCH: readonly Profile[] = [GOOGLE, X, GITHUB]

/** The launch profile for a platform name, or undefined. */
export function launch(platform: string): Profile | undefined {
  return LAUNCH.find((p) => p.platform === platform)
}

/** How many attestations a submission for this profile carries. */
export function attestationCount(profile: Profile): number {
  return (profile.token ? 1 : 0) + (profile.identity ? 1 : 0)
}

/** Governance-owned launch parameters, in seconds. */
export const MAX_FUTURE_ATTESTATION_SKEW_SECONDS = 300
export const PROOF_LIFETIME_SECONDS_X = 3600
export const PROOF_LIFETIME_SECONDS_GITHUB = 3600
