// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by scripts/regen-identity-handles.py. Do not edit.
// The source of truth is solidity/contracts/identity/handles.json.

import {HandleNormalizer} from "./HandleNormalizer.sol";

/// @notice Platform ids and the shared handle vector table.
///
/// @dev The vectors are here rather than in the test file because Rust and
///      TypeScript run the same table. A normalizer that disagrees with
///      another language fails a test instead of writing a different key.
library HandleVectors {
    /// keccak256(bytes("x"))
    bytes32 internal constant PLATFORM_X = keccak256(bytes("x"));
    /// keccak256(bytes("github"))
    bytes32 internal constant PLATFORM_GITHUB = keccak256(bytes("github"));
    /// keccak256(bytes("google"))
    bytes32 internal constant PLATFORM_GOOGLE = keccak256(bytes("google"));

    uint256 internal constant MAX_LENGTH_X = 15;
    uint256 internal constant MAX_LENGTH_GITHUB = 39;
    uint256 internal constant MAX_LENGTH_GOOGLE = 62;

    /// The normalizer rules for a platform, as `handles.json` states
    /// them.
    ///
    /// @dev Generated so a deploy, a test and a consumer cannot each
    ///      keep their own copy. Reverts on an unknown platform rather
    ///      than returning a permissive default, because a wrong rule
    ///      set writes wrong keys.
    function rulesFor(bytes32 platformId) internal pure returns (HandleNormalizer.Rules memory) {
        if (platformId == PLATFORM_X) {
            return HandleNormalizer.Rules({
                maxLength: 15, stripLeadingAt: true, isEmail: false, allowUnderscore: true, allowHyphen: false
            });
        }
        if (platformId == PLATFORM_GITHUB) {
            return HandleNormalizer.Rules({
                maxLength: 39, stripLeadingAt: true, isEmail: false, allowUnderscore: false, allowHyphen: true
            });
        }
        if (platformId == PLATFORM_GOOGLE) {
            return HandleNormalizer.Rules({
                maxLength: 62, stripLeadingAt: false, isEmail: true, allowUnderscore: false, allowHyphen: false
            });
        }
        revert("unknown platform");
    }

    /// How far ahead of the chain this platform's observations may be
    /// dated, in seconds.
    ///
    /// @dev `IdentityNames` supersedes a binding only on a strictly newer
    ///      `observedAt`, so an allowance too generous lets a proof dated
    ///      ahead hold a name until the clock catches up — and proving
    ///      again is the whole remedy the design relies on. Unknown
    ///      platforms revert, like `rulesFor`.
    function futureAllowanceFor(bytes32 platformId) internal pure returns (uint64) {
        // A notary states wall-clock time as it observes it, so the
        // observation is never ahead. Five minutes covers clock skew between
        // the notary and the chain.
        if (platformId == PLATFORM_X) return 300;
        // Same as X: notary wall-clock, five minutes for skew.
        if (platformId == PLATFORM_GITHUB) return 300;
        // The OIDC circuit exposes no `iat`, so the observation is the token's
        // `exp` — Google issues about an hour of life, and the claim therefore
        // reads roughly an hour ahead of the moment it describes.
        if (platformId == PLATFORM_GOOGLE) return 7200;
        revert("unknown platform");
    }

    /// One case from the shared table.
    struct Vector {
        string platform;
        string input;
        string output;
        bool accepted;
        uint8 errorKind;
    }

    uint8 internal constant ERROR_EMPTY = 0;
    uint8 internal constant ERROR_TOOLONG = 1;
    uint8 internal constant ERROR_BADCHARACTER = 2;
    uint8 internal constant ERROR_BADSHAPE = 3;

    uint256 internal constant COUNT = 44;

    function all() internal pure returns (Vector[] memory v) {
        v = new Vector[](44);
        v[0] = Vector({platform: "x", input: " @Alice_1 ", output: "alice_1", accepted: true, errorKind: 0});
        v[1] = Vector({platform: "x", input: "alice", output: "alice", accepted: true, errorKind: 0});
        v[2] = Vector({platform: "x", input: "@a", output: "a", accepted: true, errorKind: 0});
        v[3] = Vector({platform: "x", input: "A1_b2", output: "a1_b2", accepted: true, errorKind: 0});
        v[4] =
            Vector({platform: "x", input: "a12345678901234", output: "a12345678901234", accepted: true, errorKind: 0});
        v[5] = Vector({platform: "x", input: "a123456789012345", output: "", accepted: false, errorKind: 1});
        v[6] = Vector({platform: "x", input: "", output: "", accepted: false, errorKind: 0});
        v[7] = Vector({platform: "x", input: "   ", output: "", accepted: false, errorKind: 0});
        v[8] = Vector({platform: "x", input: "@", output: "", accepted: false, errorKind: 0});
        v[9] = Vector({platform: "x", input: "@@alice", output: "", accepted: false, errorKind: 2});
        v[10] = Vector({platform: "x", input: "alice-1", output: "", accepted: false, errorKind: 2});
        v[11] = Vector({platform: "x", input: "ali ce", output: "", accepted: false, errorKind: 2});
        v[12] = Vector({platform: "x", input: "ali\tce", output: "", accepted: false, errorKind: 2});
        v[13] = Vector({platform: "x", input: "ali\nce", output: "", accepted: false, errorKind: 2});
        v[14] = Vector({platform: "x", input: "alic\xc3\xa9", output: "", accepted: false, errorKind: 2});
        v[15] = Vector({platform: "x", input: "\talice", output: "", accepted: false, errorKind: 2});
        v[16] = Vector({platform: "x", input: "alice\t", output: "", accepted: false, errorKind: 2});
        v[17] = Vector({platform: "x", input: "\nalice", output: "", accepted: false, errorKind: 2});
        v[18] = Vector({platform: "x", input: " @ alice ", output: "", accepted: false, errorKind: 2});
        v[19] = Vector({platform: "github", input: "@Octo-Cat", output: "octo-cat", accepted: true, errorKind: 0});
        v[20] = Vector({platform: "github", input: "octocat", output: "octocat", accepted: true, errorKind: 0});
        v[21] = Vector({platform: "github", input: " OctoCat ", output: "octocat", accepted: true, errorKind: 0});
        v[22] = Vector({platform: "github", input: "a", output: "a", accepted: true, errorKind: 0});
        v[23] = Vector({platform: "github", input: "o-c", output: "o-c", accepted: true, errorKind: 0});
        v[24] = Vector({platform: "github", input: "-octocat", output: "", accepted: false, errorKind: 3});
        v[25] = Vector({platform: "github", input: "octocat-", output: "", accepted: false, errorKind: 3});
        v[26] = Vector({platform: "github", input: "octo--cat", output: "", accepted: false, errorKind: 3});
        v[27] = Vector({platform: "github", input: "octo_cat", output: "", accepted: false, errorKind: 2});
        v[28] = Vector({platform: "github", input: "-", output: "", accepted: false, errorKind: 3});
        v[29] = Vector({platform: "github", input: "", output: "", accepted: false, errorKind: 0});
        v[30] = Vector({
            platform: "github",
            input: "abcdefghijabcdefghijabcdefghijabcdefghi",
            output: "abcdefghijabcdefghijabcdefghijabcdefghi",
            accepted: true,
            errorKind: 0
        });
        v[31] = Vector({
            platform: "github",
            input: "abcdefghijabcdefghijabcdefghijabcdefghij",
            output: "",
            accepted: false,
            errorKind: 1
        });
        v[32] = Vector({platform: "github", input: "\n", output: "", accepted: false, errorKind: 2});
        v[33] = Vector({
            platform: "google",
            input: "A.B+tag@Example.COM",
            output: "a.b+tag@example.com",
            accepted: true,
            errorKind: 0
        });
        v[34] = Vector({
            platform: "google", input: "alice@example.com", output: "alice@example.com", accepted: true, errorKind: 0
        });
        v[35] = Vector({
            platform: "google", input: " Alice@Example.com ", output: "alice@example.com", accepted: true, errorKind: 0
        });
        v[36] = Vector({platform: "google", input: "@Alice@example.com", output: "", accepted: false, errorKind: 3});
        v[37] = Vector({platform: "google", input: "alice", output: "", accepted: false, errorKind: 3});
        v[38] = Vector({platform: "google", input: "@example.com", output: "", accepted: false, errorKind: 3});
        v[39] = Vector({platform: "google", input: "alice@", output: "", accepted: false, errorKind: 3});
        v[40] = Vector({platform: "google", input: "", output: "", accepted: false, errorKind: 0});
        v[41] = Vector({platform: "google", input: "ali ce@example.com", output: "", accepted: false, errorKind: 2});
        v[42] = Vector({
            platform: "google",
            input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com",
            output: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com",
            accepted: true,
            errorKind: 0
        });
        v[43] = Vector({
            platform: "google",
            input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijk@example.com",
            output: "",
            accepted: false,
            errorKind: 1
        });
    }
}
