// Generated by scripts/regen-identity-handles.py. Do not edit.
// The source of truth is solidity/contracts/identity/handles.json.

/// Platform ids and the shared handle vector table.

export interface HandleVector {
  platform: string
  input: string
  /** The normalized handle, or an empty string when the case is refused. */
  output: string
  accepted: boolean
  errorKind: number
}

/** keccak256 of this string is the platform id. */
export const PLATFORM_X_DOMAIN = 'dyaka.identity.platform.x'
/** keccak256 of this string is the platform id. */
export const PLATFORM_GITHUB_DOMAIN = 'dyaka.identity.platform.github'
/** keccak256 of this string is the platform id. */
export const PLATFORM_GOOGLE_DOMAIN = 'dyaka.identity.platform.google'

/** Bytes a x handle may have after normalization. */
export const MAX_LENGTH_X = 15
/** Bytes a github handle may have after normalization. */
export const MAX_LENGTH_GITHUB = 39
/** Bytes a google handle may have after normalization. */
export const MAX_LENGTH_GOOGLE = 62

/** Remove one leading `@`. */
export const STRIP_LEADING_AT_X = true
/** Validate as an address instead of a bare handle. */
export const IS_EMAIL_X = false
/** Allow `_`. */
export const ALLOW_UNDERSCORE_X = true
/** Allow `-`, but not leading, trailing or doubled. */
export const ALLOW_HYPHEN_X = false
/** Remove one leading `@`. */
export const STRIP_LEADING_AT_GITHUB = true
/** Validate as an address instead of a bare handle. */
export const IS_EMAIL_GITHUB = false
/** Allow `_`. */
export const ALLOW_UNDERSCORE_GITHUB = false
/** Allow `-`, but not leading, trailing or doubled. */
export const ALLOW_HYPHEN_GITHUB = true
/** Remove one leading `@`. */
export const STRIP_LEADING_AT_GOOGLE = false
/** Validate as an address instead of a bare handle. */
export const IS_EMAIL_GOOGLE = true
/** Allow `_`. */
export const ALLOW_UNDERSCORE_GOOGLE = false
/** Allow `-`, but not leading, trailing or doubled. */
export const ALLOW_HYPHEN_GOOGLE = false

/// A notary states wall-clock time as it observes it, so the
/// observation is never ahead. Five minutes covers clock skew between
/// the notary and the chain.
export const FUTURE_ALLOWANCE_X = 300
/// Same as X: notary wall-clock, five minutes for skew.
export const FUTURE_ALLOWANCE_GITHUB = 300
/// The OIDC circuit exposes no `iat`, so the observation is the token's
/// `exp` — Google issues about an hour of life, and the claim therefore
/// reads roughly an hour ahead of the moment it describes.
export const FUTURE_ALLOWANCE_GOOGLE = 7200

export const ERROR_EMPTY = 0
export const ERROR_TOOLONG = 1
export const ERROR_BADCHARACTER = 2
export const ERROR_BADSHAPE = 3

export const HANDLE_VECTORS: HandleVector[] = [
  { platform: "x", input: " @Alice_1 ", output: "alice_1", accepted: true, errorKind: 0 },
  { platform: "x", input: "alice", output: "alice", accepted: true, errorKind: 0 },
  { platform: "x", input: "@a", output: "a", accepted: true, errorKind: 0 },
  { platform: "x", input: "A1_b2", output: "a1_b2", accepted: true, errorKind: 0 },
  { platform: "x", input: "a12345678901234", output: "a12345678901234", accepted: true, errorKind: 0 },
  { platform: "x", input: "a123456789012345", output: "", accepted: false, errorKind: 1 },
  { platform: "x", input: "", output: "", accepted: false, errorKind: 0 },
  { platform: "x", input: "   ", output: "", accepted: false, errorKind: 0 },
  { platform: "x", input: "@", output: "", accepted: false, errorKind: 0 },
  { platform: "x", input: "@@alice", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "alice-1", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "ali ce", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "ali\tce", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "ali\nce", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "alic\u00e9", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "\talice", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "alice\t", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: "\nalice", output: "", accepted: false, errorKind: 2 },
  { platform: "x", input: " @ alice ", output: "", accepted: false, errorKind: 2 },
  { platform: "github", input: "@Octo-Cat", output: "octo-cat", accepted: true, errorKind: 0 },
  { platform: "github", input: "octocat", output: "octocat", accepted: true, errorKind: 0 },
  { platform: "github", input: " OctoCat ", output: "octocat", accepted: true, errorKind: 0 },
  { platform: "github", input: "a", output: "a", accepted: true, errorKind: 0 },
  { platform: "github", input: "o-c", output: "o-c", accepted: true, errorKind: 0 },
  { platform: "github", input: "-octocat", output: "", accepted: false, errorKind: 3 },
  { platform: "github", input: "octocat-", output: "", accepted: false, errorKind: 3 },
  { platform: "github", input: "octo--cat", output: "", accepted: false, errorKind: 3 },
  { platform: "github", input: "octo_cat", output: "", accepted: false, errorKind: 2 },
  { platform: "github", input: "-", output: "", accepted: false, errorKind: 3 },
  { platform: "github", input: "", output: "", accepted: false, errorKind: 0 },
  { platform: "github", input: "abcdefghijabcdefghijabcdefghijabcdefghi", output: "abcdefghijabcdefghijabcdefghijabcdefghi", accepted: true, errorKind: 0 },
  { platform: "github", input: "abcdefghijabcdefghijabcdefghijabcdefghij", output: "", accepted: false, errorKind: 1 },
  { platform: "github", input: "\n", output: "", accepted: false, errorKind: 2 },
  { platform: "google", input: "A.B+tag@Example.COM", output: "a.b+tag@example.com", accepted: true, errorKind: 0 },
  { platform: "google", input: "alice@example.com", output: "alice@example.com", accepted: true, errorKind: 0 },
  { platform: "google", input: " Alice@Example.com ", output: "alice@example.com", accepted: true, errorKind: 0 },
  { platform: "google", input: "@Alice@example.com", output: "", accepted: false, errorKind: 3 },
  { platform: "google", input: "alice", output: "", accepted: false, errorKind: 3 },
  { platform: "google", input: "@example.com", output: "", accepted: false, errorKind: 3 },
  { platform: "google", input: "alice@", output: "", accepted: false, errorKind: 3 },
  { platform: "google", input: "", output: "", accepted: false, errorKind: 0 },
  { platform: "google", input: "ali ce@example.com", output: "", accepted: false, errorKind: 2 },
  { platform: "google", input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com", output: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com", accepted: true, errorKind: 0 },
  { platform: "google", input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijk@example.com", output: "", accepted: false, errorKind: 1 },
]
