#!/usr/bin/env python3
"""Regenerate the identity platform constants and the handle vector table.

`solidity/contracts/handles/handles.json` is the single source of truth. Edit
it, then run this script. These files are written and never drift apart:

    solidity/contracts/handles/HandlePlatforms.sol        # Solidity constants (production)
    solidity/contracts/handles/HandleVectors.sol          # Solidity vectors (tests)
    rust/identity/src/handle_vectors.rs                    # Rust constants + vectors
    ts/packages/contracts/src/identity/handleVectors.ts    # TypeScript constants + vectors
    <libid-circuits>/lib/identity/src/table.nr             # Noir constants, with --noir-out <that path>
    <libid-circuits>/lib/identity/src/table_tests.nr       # Noir vector tests, beside it

Every output carries the SHA-256 of handles.json, so a consumer holding a
generated file from one table and a contract from another can tell.

Every handleNode and idNode in the table is recomputed here with hashlib and
must match what the table states: the stored nodes are the independent
reference every language is tested against, so a wrong one is refused before
it is copied anywhere.

The normalizer itself is hand written in each language. Only the constants and the vectors
come from here. That is the point: several implementations, one vector table,
so a difference between them fails a test instead of writing a different key
on chain.

Run: ./scripts/regen-identity-handles.py [--noir-out ../libid-circuits/lib/identity/src/table.nr]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
import textwrap
import sys
from typing import Any

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SOLIDITY_ROOT = REPO_ROOT / "solidity"
SOURCE = SOLIDITY_ROOT / "contracts" / "handles" / "handles.json"

SOL_OUT = SOLIDITY_ROOT / "contracts" / "handles" / "HandlePlatforms.sol"
SOL_VECTORS_OUT = SOLIDITY_ROOT / "contracts" / "handles" / "HandleVectors.sol"
RUST_OUT = REPO_ROOT / "rust" / "identity" / "src" / "handle_vectors.rs"
TS_OUT = REPO_ROOT / "ts" / "packages" / "contracts" / "src" / "identity" / "handleVectors.ts"

BANNER = [
    "Generated by libID-contracts' scripts/regen-identity-handles.py. Do not edit.",
    "The source of truth is libID-contracts' solidity/contracts/handles/handles.json.",
]


def header(comment: str) -> str:
    return "".join(f"{comment} {line}\n" for line in BANNER)


def as_lines(note: Any) -> list[str]:
    """A note from handles.json as comment lines.

    The file writes a note either as one string or as a list of lines, and both
    spellings appear in it already.
    """
    if not note:
        return []
    if isinstance(note, list):
        return [str(line) for line in note]
    return textwrap.wrap(str(note), width=68)


def handle_flags(platform: dict[str, Any]) -> dict[str, bool]:
    """The normalizer's boolean rules for one platform. Every generator reads
    them here, so a flag added here reaches every output at once."""
    return {
        "isEmail": platform.get("shape") == "email",
        "allowUnderscore": bool(platform.get("allowUnderscore", False)),
        "allowHyphen": bool(platform.get("allowHyphen", False)),
    }


def table_sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def check_tags(spec: dict[str, Any]) -> None:
    """Refuse tags two keys could share.

    Nodes are global -- no platform id sits beside them -- so the tags alone
    keep two platforms, and an id and a handle, apart. A repeated tag would
    put two keyspaces on one; a tag that is a prefix of another lets
    SHA256(a || "x.y") equal SHA256(a.x || "y") whenever the bytes line up.
    """
    tags = [t for p in spec["platforms"] for t in (p["tags"]["userId"], p["tags"]["handle"])]
    for i, a in enumerate(tags):
        for b in tags[i + 1:]:
            if a == b or a.startswith(b) or b.startswith(a):
                raise SystemExit(f"ERROR: tags {a!r} and {b!r} overlap; tags must be distinct and prefix-free")


def check_nodes(spec: dict[str, Any]) -> None:
    """Refuse a table whose stored nodes are not SHA256(tag || value).

    A handle vector is hashed by its output under the handle tag, an id
    vector by its input under the user-id tag; a refused vector of either
    kind carries no node.
    """
    tags = {p["key"]: p["tags"] for p in spec["platforms"]}
    cases = [(vec, "handle", "handleNode", vec.get("output")) for vec in spec["vectors"]] + [
        (vec, "userId", "idNode", None if "error" in vec else vec["input"]) for vec in spec["idVectors"]
    ]
    for vec, tag, field, value in cases:
        if value is None:
            if field in vec:
                raise SystemExit(f"ERROR: refused {vec['platform']} {vec['input']!r} carries {field}")
            continue
        want = "0x" + hashlib.sha256((tags[vec["platform"]][tag] + value).encode()).hexdigest()
        if vec.get(field) != want:
            raise SystemExit(
                f"ERROR: {vec['platform']} {vec['input']!r}: {field} is not "
                f"SHA256(tag || value); expected {want}"
            )


def id_flags(platform: dict[str, Any]) -> tuple[int, bool, bool]:
    """(max length, decimal, leading zero allowed) for a platform's ids."""
    rules = platform["id"]
    return rules["maxLength"], rules["shape"] == "decimal", bool(rules["leadingZero"])


def sol_escape(value: str) -> str:
    """Solidity string literal. Escape the bytes a source file cannot hold."""
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            # Solidity has no \u escape in a plain string, so emit the UTF-8
            # bytes one at a time. A vector that carries a non-ASCII byte is
            # there to prove the normalizer refuses it.
            out.extend(f"\\x{b:02x}" for b in ch.encode("utf-8"))
        else:
            out.append(ch)
    return "".join(out)


def rust_escape(value: str) -> str:
    """Rust string literal.

    Rust writes a code point as `\\u{e9}`, not as JSON's `\\u00e9`, so the
    escapes cannot be borrowed from `json.dumps` unchanged.
    """
    out = []
    for ch in value:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return "".join(out)


def error_index(errors: list[dict[str, Any]], key: str) -> int:
    for i, err in enumerate(errors):
        if err["key"] == key:
            return i
    raise SystemExit(f"ERROR: unknown error kind {key!r} in a vector")


def gen_sol(spec: dict[str, Any], digest: str) -> str:
    """The constants production code reads."""
    platforms = spec["platforms"]

    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.20;",
        "",
        header("//").rstrip("\n"),
        "",
        'import {HandleNormalizer} from "./HandleNormalizer.sol";',
        "",
        "/// @notice Each platform `handles.json` names: its id, its handle rules and",
        "///         its node tags, as the production contracts read them.",
        "///",
        "/// @dev The vector table the languages share is `HandleVectors`, which",
        "///      only tests read.",
        "library HandlePlatforms {",
        "    /// @notice `handles.json` names no such platform.",
        "    error UnknownPlatform(bytes32 platformId);",
        "",
        "    /// SHA-256 of the handles.json this file was generated from.",
        f"    bytes32 internal constant TABLE_SHA256 = 0x{digest};",
        "",
    ]

    for p in platforms:
        name = p["key"].upper()
        lines.append(f'    /// keccak256(bytes("{p["key"]}"))')
        lines.append(
            f"    bytes32 internal constant PLATFORM_{name} ="
            f' keccak256(bytes("{p["key"]}"));'
        )
    lines.append("")

    for p in platforms:
        name = p["key"].upper()
        lines.append(f'    /// `{p["tags"]["userId"]}`: an id node is SHA256 of this, then the id.')
        lines.append(f'    bytes internal constant USER_ID_TAG_{name} = "{p["tags"]["userId"]}";')
        lines.append(f'    /// `{p["tags"]["handle"]}`: a handle node is SHA256 of this, then the')
        lines.append("    /// normalized handle.")
        lines.append(f'    bytes internal constant HANDLE_TAG_{name} = "{p["tags"]["handle"]}";')
    lines.append("")
    lines.append("    /// Whether `handles.json` names this platform.")
    lines.append("    function knows(bytes32 platformId) internal pure returns (bool) {")
    lines.append(
        "        return "
        + " || ".join(f"platformId == PLATFORM_{p['key'].upper()}" for p in platforms)
        + ";"
    )
    lines.append("    }")
    lines.append("")
    lines.append("    /// The tag a platform's id nodes are hashed under.")
    lines.append("    ///")
    lines.append("    /// @dev Reverts on an unknown platform, as `rulesFor` does.")
    lines.append(
        "    function userIdTagFor(bytes32 platformId) internal pure returns (bytes memory) {"
    )
    for p in platforms:
        name = p["key"].upper()
        lines.append(f"        if (platformId == PLATFORM_{name}) return USER_ID_TAG_{name};")
    lines.append("        revert UnknownPlatform(platformId);")
    lines.append("    }")
    lines.append("")
    lines.append("    /// The tag a platform's handle nodes are hashed under.")
    lines.append("    ///")
    lines.append("    /// @dev Reverts on an unknown platform, as `rulesFor` does.")
    lines.append(
        "    function handleTagFor(bytes32 platformId) internal pure returns (bytes memory) {"
    )
    for p in platforms:
        name = p["key"].upper()
        lines.append(f"        if (platformId == PLATFORM_{name}) return HANDLE_TAG_{name};")
    lines.append("        revert UnknownPlatform(platformId);")
    lines.append("    }")
    lines.append("")
    lines += [
        "    /// The normalizer rules for a platform, as `handles.json` states",
        "    /// them.",
        "    ///",
        "    /// @dev Generated so a deploy, a test and a consumer cannot each",
        "    ///      keep their own copy. Reverts on an unknown platform rather",
        "    ///      than returning a permissive default, because a wrong rule",
        "    ///      set writes wrong nodes.",
        "    function rulesFor(bytes32 platformId) internal pure returns (HandleNormalizer.Rules memory rules) {",
        "        (rules,) = _handleKeys(platformId);",
        "    }",
        "",
        "    /// The handle typed text names on a platform, normalized with its",
        "    /// rules, and the node it is bound under, hashed under its tag.",
        "    ///",
        "    /// @dev Reverts `UnusableHandle` for text the rules refuse, and",
        "    ///      `UnknownPlatform`.",
        "    function handleNodeOf(bytes32 platformId, string memory raw)",
        "        internal",
        "        pure",
        "        returns (string memory normalized, bytes32 handleNode)",
        "    {",
        "        (HandleNormalizer.Rules memory rules, bytes memory tag) = _handleKeys(platformId);",
        "        return HandleNormalizer.nodeOf(raw, rules, tag);",
        "    }",
        "",
        "    /// `handleNodeOf`, reporting what the rules refuse instead of reverting.",
        "    ///",
        "    /// @dev Reverts `UnknownPlatform`.",
        "    function tryHandleNodeOf(bytes32 platformId, string memory raw)",
        "        internal",
        "        pure",
        "        returns (HandleNormalizer.Problem problem, bytes32 handleNode)",
        "    {",
        "        (HandleNormalizer.Rules memory rules, bytes memory tag) = _handleKeys(platformId);",
        "        return HandleNormalizer.tryNodeOf(raw, rules, tag);",
        "    }",
        "",
        "    function _handleKeys(bytes32 platformId)",
        "        private",
        "        pure",
        "        returns (HandleNormalizer.Rules memory rules, bytes memory tag)",
        "    {",
    ]
    for p in platforms:
        name = p["key"].upper()
        flags = ", ".join(f"{k}: {str(v).lower()}" for k, v in handle_flags(p).items())
        lines.append(f"        if (platformId == PLATFORM_{name}) {{")
        lines.append(f"            rules = HandleNormalizer.Rules({{maxLength: {p['maxLength']}, {flags}}});")
        lines.append(f"            return (rules, HANDLE_TAG_{name});")
        lines.append("        }")
    lines.append("        revert UnknownPlatform(platformId);")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_sol_vectors(spec: dict[str, Any], digest: str) -> str:
    """The test vectors, apart from the constants production code reads."""
    errors = spec["errors"]
    vectors = spec["vectors"]

    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.20;",
        "",
        header("//").rstrip("\n"),
        f"// Table SHA-256: 0x{digest} (HandlePlatforms.TABLE_SHA256).",
        "",
        "/// @notice The shared handle vector table, for tests.",
        "///",
        "/// @dev The vectors are here rather than in a test file because Rust and",
        "///      TypeScript run the same table. A normalizer that disagrees with",
        "///      another language fails a test instead of writing a different node.",
        "///      Production code reads `HandlePlatforms` and never this file.",
        "library HandleVectors {",
    ]
    lines.append("    /// One case from the shared table.")
    lines.append("    struct Vector {")
    lines.append("        string platform;")
    lines.append("        string input;")
    lines.append("        string output;")
    lines.append("        bool accepted;")
    lines.append("        uint8 errorKind;")
    lines.append("        bytes32 handleNode;")
    lines.append("    }")
    lines.append("")

    for i, err in enumerate(errors):
        lines.append(f"    uint8 internal constant ERROR_{err['key'].upper()} = {i};")
    lines.append("")

    lines.append(f"    uint256 internal constant COUNT = {len(vectors)};")
    lines.append("")
    lines.append("    function all() internal pure returns (Vector[] memory v) {")
    lines.append(f"        v = new Vector[]({len(vectors)});")
    # Named fields, as the Rust and TypeScript tables already have them: a
    # literal that names its fields cannot be silently reordered against the
    # struct, which is what `forge lint` (named-struct-fields) is for.
    for i, vec in enumerate(vectors):
        accepted = "output" in vec
        out = sol_escape(vec.get("output", ""))
        kind = "0" if accepted else str(error_index(errors, vec["error"]))
        lines.append(
            f'        v[{i}] = Vector({{platform: "{vec["platform"]}",'
            f' input: "{sol_escape(vec["input"])}", output: "{out}",'
            f' accepted: {"true" if accepted else "false"}, errorKind: {kind},'
            f' handleNode: {vec.get("handleNode", "bytes32(0)")}}});'
        )
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_rust(spec: dict[str, Any], digest: str) -> str:
    platforms = spec["platforms"]
    errors = spec["errors"]
    vectors = spec["vectors"]

    lines = [
        header("//").rstrip("\n"),
        "",
        "//! Platform ids and the shared handle vector table.",
        "",
        "/// One case from the shared table.",
        "pub struct Vector {",
        "    /// Platform key, as written in the source table.",
        "    pub platform: &'static str,",
        "    /// The handle exactly as a caller supplied it.",
        "    pub input: &'static str,",
        "    /// The normalized handle, or an empty string when the case is refused.",
        "    pub output: &'static str,",
        "    /// Whether the transform accepts this case.",
        "    pub accepted: bool,",
        "    /// Which refusal the case expects, when it is refused.",
        "    pub error_kind: u8,",
        "    /// SHA256(handle tag || output), hex, or empty when the case is refused.",
        "    pub handle_node: &'static str,",
        "}",
        "",
        "/// One id case from the shared table.",
        "pub struct IdVector {",
        "    /// Platform key, as written in the source table.",
        "    pub platform: &'static str,",
        "    /// The id exactly as the platform sent it.",
        "    pub input: &'static str,",
        "    /// Whether the id rules accept this case.",
        "    pub accepted: bool,",
        "    /// Which refusal the case expects, when it is refused.",
        "    pub error_kind: u8,",
        "    /// SHA256(id tag || input), hex, or empty when the case is refused.",
        "    pub id_node: &'static str,",
        "}",
        "",
        "/// A platform `handles.json` names: its key, its node tags and its rules.",
        "pub struct Platform {",
        "    /// keccak256 of this string is the platform id.",
        "    pub key: &'static str,",
        "    /// An id node is SHA256 of this tag, then the id.",
        "    pub user_id_tag: &'static str,",
        "    /// A handle node is SHA256 of this tag, then the normalized handle.",
        "    pub handle_tag: &'static str,",
        "    /// What a handle may be.",
        "    pub rules: crate::Rules,",
        "    /// What an id may be.",
        "    pub id_rules: crate::IdRules,",
        "}",
        "",
        "/// SHA-256 of the handles.json this file was generated from.",
        f'pub const TABLE_SHA256: &str = "{digest}";',
        "",
    ]

    for p in platforms:
        lines.append("/// keccak256 of this string is the platform id.")
        lines.append(
            f'pub const PLATFORM_{p["key"].upper()}_KEY: &str = "{p["key"]}";'
        )
    lines.append("")

    for p in platforms:
        name = p["key"].upper()
        max_len, decimal, leading = id_flags(p)
        rules = handle_flags(p)
        lines += [
            f"/// {p['key']}, as `handles.json` states it.",
            f"pub const PLATFORM_{name}: Platform = Platform {{",
            f"    key: PLATFORM_{name}_KEY,",
            f'    user_id_tag: "{p["tags"]["userId"]}",',
            f'    handle_tag: "{p["tags"]["handle"]}",',
            "    rules: crate::Rules {",
            f"        max_length: {p['maxLength']},",
            f"        is_email: {str(rules['isEmail']).lower()},",
            f"        allow_underscore: {str(rules['allowUnderscore']).lower()},",
            f"        allow_hyphen: {str(rules['allowHyphen']).lower()},",
            "    },",
            "    id_rules: crate::IdRules {",
            f"        max_length: {max_len},",
            f"        decimal: {str(decimal).lower()},",
            f"        leading_zero: {str(leading).lower()},",
            "    },",
            "};",
        ]
    lines += [
        "",
        "/// Every platform, in table order.",
        f"pub static PLATFORMS: [Platform; {len(platforms)}] = ["
        + ", ".join(f"PLATFORM_{p['key'].upper()}" for p in platforms)
        + "];",
        "",
        "/// The platform with this key, if the table names it.",
        "pub fn platform(key: &str) -> Option<&'static Platform> {",
        "    PLATFORMS.iter().find(|p| p.key == key)",
        "}",
        "",
    ]

    for i, err in enumerate(errors):
        lines.append(f"/// {err['note']}")
        lines.append(f"pub const ERROR_{err['key'].upper()}: u8 = {i};")
    lines.append("")

    lines.append("/// Every case, shared with Solidity and TypeScript.")
    lines.append(f"pub const VECTORS: [Vector; {len(vectors)}] = [")
    for vec in vectors:
        accepted = "output" in vec
        out = rust_escape(vec.get("output", ""))
        kind = 0 if accepted else error_index(errors, vec["error"])
        lines.append("    Vector {")
        lines.append(f'        platform: "{vec["platform"]}",')
        lines.append(f'        input: "{rust_escape(vec["input"])}",')
        lines.append(f'        output: "{out}",')
        lines.append(f"        accepted: {'true' if accepted else 'false'},")
        lines.append(f"        error_kind: {kind},")
        lines.append(f'        handle_node: "{vec.get("handleNode", "")}",')
        lines.append("    },")
    lines.append("];")
    lines.append("")
    id_vectors = spec["idVectors"]
    lines.append("/// Every id case, shared with TypeScript and Noir.")
    lines.append(f"pub const ID_VECTORS: [IdVector; {len(id_vectors)}] = [")
    for vec in id_vectors:
        accepted = "error" not in vec
        kind = 0 if accepted else error_index(errors, vec["error"])
        lines.append("    IdVector {")
        lines.append(f'        platform: "{vec["platform"]}",')
        lines.append(f'        input: "{rust_escape(vec["input"])}",')
        lines.append(f"        accepted: {'true' if accepted else 'false'},")
        lines.append(f"        error_kind: {kind},")
        lines.append(f'        id_node: "{vec.get("idNode", "")}",')
        lines.append("    },")
    lines.append("];")
    return "\n".join(lines) + "\n"


def gen_ts(spec: dict[str, Any], digest: str) -> str:
    platforms = spec["platforms"]
    errors = spec["errors"]
    vectors = spec["vectors"]

    lines = [
        header("//").rstrip("\n"),
        "",
        "/// Platform ids and the shared handle vector table.",
        "",
        "import type { Rules } from './handle.js'",
        "import type { IdRules } from './node.js'",
        "",
        "export interface HandleVector {",
        "  platform: string",
        "  input: string",
        "  /** The normalized handle, or an empty string when the case is refused. */",
        "  output: string",
        "  accepted: boolean",
        "  errorKind: number",
        "  /** SHA256(handle tag || output), hex, or empty when the case is refused. */",
        "  handleNode: string",
        "}",
        "",
        "export interface IdVector {",
        "  platform: string",
        "  /** The id exactly as the platform sent it. */",
        "  input: string",
        "  accepted: boolean",
        "  errorKind: number",
        "  /** SHA256(id tag || input), hex, or empty when the case is refused. */",
        "  idNode: string",
        "}",
        "",
        "/** A platform `handles.json` names: its key, its node tags and its rules. */",
        "export interface Platform {",
        "  /** keccak256 of this string is the platform id. */",
        "  key: string",
        "  /** An id node is SHA256 of this tag, then the id. */",
        "  userIdTag: string",
        "  /** A handle node is SHA256 of this tag, then the normalized handle. */",
        "  handleTag: string",
        "  rules: Rules",
        "  idRules: IdRules",
        "}",
        "",
        "/** SHA-256 of the handles.json this file was generated from. */",
        f"export const TABLE_SHA256 = '{digest}'",
        "",
    ]

    for p in platforms:
        lines.append("/** keccak256 of this string is the platform id. */")
        lines.append(f"export const PLATFORM_{p['key'].upper()}_KEY = '{p['key']}'")
    lines.append("")

    for p in platforms:
        name = p["key"].upper()
        max_len, decimal, leading = id_flags(p)
        rules = handle_flags(p)
        lines += [
            f"export const PLATFORM_{name}: Platform = {{",
            f"  key: PLATFORM_{name}_KEY,",
            f"  userIdTag: '{p['tags']['userId']}',",
            f"  handleTag: '{p['tags']['handle']}',",
            "  rules: {",
            f"    maxLength: {p['maxLength']},",
            f"    isEmail: {str(rules['isEmail']).lower()},",
            f"    allowUnderscore: {str(rules['allowUnderscore']).lower()},",
            f"    allowHyphen: {str(rules['allowHyphen']).lower()},",
            "  },",
            f"  idRules: {{ maxLength: {max_len}, decimal: {str(decimal).lower()}, leadingZero: {str(leading).lower()} }},",
            "}",
        ]
    lines += [
        "",
        "/** Every platform, in table order. */",
        "export const PLATFORMS: readonly Platform[] = ["
        + ", ".join(f"PLATFORM_{p['key'].upper()}" for p in platforms)
        + "]",
        "",
        "/** The platform with this key, if the table names it. */",
        "export function platform(key: string): Platform | undefined {",
        "  return PLATFORMS.find((p) => p.key === key)",
        "}",
        "",
    ]

    for i, err in enumerate(errors):
        lines.append(f"export const ERROR_{err['key'].upper()} = {i}")
    lines.append("")

    lines.append("export const HANDLE_VECTORS: HandleVector[] = [")
    for vec in vectors:
        accepted = "output" in vec
        out = json.dumps(vec.get("output", ""))
        kind = 0 if accepted else error_index(errors, vec["error"])
        lines.append(
            f"  {{ platform: {json.dumps(vec['platform'])},"
            f" input: {json.dumps(vec['input'])},"
            f" output: {out},"
            f" accepted: {'true' if accepted else 'false'},"
            f" errorKind: {kind},"
            f" handleNode: {json.dumps(vec.get('handleNode', ''))} }},"
        )
    lines.append("]")
    lines.append("")
    lines.append("export const ID_VECTORS: IdVector[] = [")
    for vec in spec["idVectors"]:
        accepted = "error" not in vec
        kind = 0 if accepted else error_index(errors, vec["error"])
        lines.append(
            f"  {{ platform: {json.dumps(vec['platform'])},"
            f" input: {json.dumps(vec['input'])},"
            f" accepted: {'true' if accepted else 'false'},"
            f" errorKind: {kind},"
            f" idNode: {json.dumps(vec.get('idNode', ''))} }},"
        )
    lines.append("]")
    return "\n".join(lines) + "\n"


NOIR_ERRORS = {
    "Empty": "is empty",
    "TooLong": "too long",
    "BadCharacter": "byte not allowed",
    "BadShape": "shape not allowed",
}


def noir_bytes(value: bytes) -> str:
    return "[" + ", ".join(f"0x{b:02x}" for b in value) + "]"


NOIR_ESCAPES = {0x09: "\\t", 0x0A: "\\n", 0x22: '\\"'}


def noir_string(value: bytes) -> str | None:
    """`value` as a Noir string literal, or None when it holds a byte a
    literal cannot spell plainly: a backslash, a control byte other than tab
    and newline, or anything above 0x7e."""
    out = []
    for b in value:
        if b in NOIR_ESCAPES:
            out.append(NOIR_ESCAPES[b])
        elif 0x20 <= b <= 0x7E and b != 0x5C:
            out.append(chr(b))
        else:
            return None
    return '"' + "".join(out) + '"'


def noir_halves(node: str) -> str:
    """A node from the table as the `[high, low]` Fields `node_halves` returns."""
    return f"[0x{node[2:34]}, 0x{node[34:]}]"


def gen_noir(spec: dict[str, Any], digest: str) -> str:
    """The circuit library's constants: what every circuit compiles against,
    and what a circuits release ships as `handles-table.nr`."""
    lines = [
        header("//").rstrip("\n"),
        "",
        "// Platform tags and rules, for the identity circuits. The algorithm is",
        "// lib.nr's; table_tests.nr runs it against the shared vector table.",
        "",
        "use crate::{HandleRules, IdRules};",
        "",
        "/// SHA-256 of the handles.json this file was generated from.",
        f'pub global TABLE_SHA256: str<64> = "{digest}";',
        "",
    ]
    for p in spec["platforms"]:
        name = p["key"].upper()
        id_tag = p["tags"]["userId"].encode()
        handle_tag = p["tags"]["handle"].encode()
        max_len, decimal, leading = id_flags(p)
        is_email = p.get("shape") == "email"
        lines += [
            f"/// `{p['tags']['userId']}`",
            f"pub global USER_ID_TAG_{name}: [u8; {len(id_tag)}] = {noir_bytes(id_tag)};",
            f"/// `{p['tags']['handle']}`",
            f"pub global HANDLE_TAG_{name}: [u8; {len(handle_tag)}] = {noir_bytes(handle_tag)};",
            f"pub global MAX_HANDLE_{name}: u32 = {p['maxLength']};",
            f"pub global MAX_ID_{name}: u32 = {max_len};",
            f"pub global HANDLE_RULES_{name}: HandleRules = HandleRules {{",
            f"    max_len: {p['maxLength']},",
            f"    allow_underscore: {str(bool(p.get('allowUnderscore')) and not is_email).lower()},",
            f"    allow_hyphen: {str(bool(p.get('allowHyphen')) and not is_email).lower()},",
            f"    is_email: {str(is_email).lower()},",
            "};",
            f"pub global ID_RULES_{name}: IdRules = IdRules {{",
            f"    max_len: {max_len},",
            f"    decimal: {str(decimal).lower()},",
            f"    leading_zero: {str(leading).lower()},",
            "};",
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def gen_noir_tests(spec: dict[str, Any], digest: str) -> str:
    """One Noir test per vector, run against lib.nr's algorithm.

    A refused vector is a `should_fail_with` test on the reason every other
    language gives. A value longer than the platform allows does not fit the
    circuit's buffer at all; its test hands the buffer's worth of bytes with
    the true length, which is the claim a dishonest witness would make.
    """
    by_key = {p["key"]: p for p in spec["platforms"]}
    lines = [
        header("//").rstrip("\n"),
        f"// Table SHA-256: {digest} (table::TABLE_SHA256).",
        "",
        "// The shared vector table, run against lib.nr's algorithm.",
        "",
        "use crate::{check_id, node_halves, normalize_handle, table};",
        "use crate::testing::padded;",
        "",
    ]

    def buffer(value: bytes, size: int) -> list[str]:
        """The padded witness, as a string literal when one spells it."""
        kept = value[:size]
        literal = noir_string(kept)
        if literal is not None:
            return [f"    let raw: [u8; {size}] = padded({literal}.as_bytes());"]
        return [
            f"    // {json.dumps(value.decode(), ensure_ascii=False)}",
            f"    let raw: [u8; {size}] = {noir_bytes(kept + bytes(size - len(kept)))};",
        ]

    for i, vec in enumerate(spec["vectors"]):
        name = vec["platform"].upper()
        size = by_key[vec["platform"]]["maxLength"]
        raw = vec["input"].encode()
        attr = "#[test]"
        if "error" in vec:
            attr = f'#[test(should_fail_with = "handle {NOIR_ERRORS[vec["error"]]}")]'
        lines.append(attr)
        lines.append(f"fn handle_{vec['platform']}_{i}() {{")
        lines += buffer(raw, size)
        lines.append(
            f"    let out = normalize_handle(raw, {len(raw)}, table::HANDLE_RULES_{name});"
        )
        if "output" in vec:
            lines.append(
                f"    assert(node_halves(table::HANDLE_TAG_{name}, out, {len(raw)})"
                f" == {noir_halves(vec['handleNode'])});"
            )
        else:
            lines.append("    let _ = out;")
        lines.append("}")
        lines.append("")

    for i, vec in enumerate(spec["idVectors"]):
        name = vec["platform"].upper()
        size, _, _ = id_flags(by_key[vec["platform"]])
        raw = vec["input"].encode()
        attr = "#[test]"
        if "error" in vec:
            attr = f'#[test(should_fail_with = "id {NOIR_ERRORS[vec["error"]]}")]'
        lines.append(attr)
        lines.append(f"fn id_{vec['platform']}_{i}() {{")
        lines += buffer(raw, size)
        lines.append(f"    check_id(raw, {len(raw)}, table::ID_RULES_{name});")
        if "idNode" in vec:
            lines.append(
                f"    assert(node_halves(table::USER_ID_TAG_{name}, raw, {len(raw)})"
                f" == {noir_halves(vec['idNode'])});"
            )
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def noir_shape(text: str) -> str:
    """Noir source with formatting and comments removed: whitespace, `//`
    comments, and the trailing commas `nargo fmt` adds, so two renderings of
    one table compare equal and only what the circuit compiles is compared.
    String literals are kept byte for byte."""
    import re

    out = []
    i = 0
    while i < len(text):
        c = text[i]
        if c == '"':
            j = i + 1
            while text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            out.append(text[i : j + 1])
            i = j + 1
        elif text.startswith("//", i):
            i = text.find("\n", i)
            if i == -1:
                break
        elif c.isspace():
            i += 1
        else:
            out.append(c)
            i += 1
    return re.sub(r",([\]\})])", r"\1", "".join(out))


def noir_formatted(text: str) -> str:
    """Run the emitted Noir through `nargo fmt`, as the Solidity goes through
    `forge fmt`: the circuits' CI checks formatting, so the committed file has
    to be exactly what this script produces formatted.
    """
    import tempfile

    nargo = shutil.which("nargo")
    if nargo is None:
        print("ERROR: nargo is not on PATH, so the Noir cannot be formatted", file=sys.stderr)
        raise SystemExit(1)
    with tempfile.TemporaryDirectory() as tmp:
        package = pathlib.Path(tmp)
        (package / "src").mkdir()
        (package / "Nargo.toml").write_text(
            '[package]\nname = "table"\ntype = "lib"\nauthors = [""]\n[dependencies]\n'
        )
        source = package / "src" / "lib.nr"
        source.write_text(text, encoding="utf-8")
        done = subprocess.run([nargo, "fmt"], cwd=package, capture_output=True, text=True)
        if done.returncode != 0:
            print(f"ERROR: nargo fmt failed:\n{done.stderr}", file=sys.stderr)
            raise SystemExit(1)
        return source.read_text(encoding="utf-8")


def sol_formatted(text: str) -> str:
    """Run the emitted Solidity through `forge fmt`.

    Matching the formatter by hand is a losing game — it collapses a struct
    literal onto one line when it fits and splits it when it does not — and
    losing it means the committed file is never what this script produces, so
    `--check` can only ever be red. Formatting here makes the two the same
    thing.
    """
    forge = shutil.which("forge")
    if forge is None:
        print("ERROR: forge is not on PATH, so the Solidity cannot be formatted", file=sys.stderr)
        raise SystemExit(1)

    done = subprocess.run(
        [forge, "fmt", "--raw", "-"],
        input=text,
        capture_output=True,
        text=True,
        cwd=SOLIDITY_ROOT,
    )
    if done.returncode != 0:
        print(f"ERROR: forge fmt failed:\n{done.stderr}", file=sys.stderr)
        raise SystemExit(1)
    return done.stdout


def display(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Write nothing; exit non-zero if any generated file is out of date.",
    )
    parser.add_argument(
        "--noir-out",
        type=pathlib.Path,
        help="Also write (or, with --check, compare) the Noir table at this path,"
        " normally <libid-circuits>/lib/identity/src/table.nr, and its vector"
        " tests beside it as table_tests.nr.",
    )
    parser.add_argument(
        "--compare-noir",
        type=pathlib.Path,
        help="Exit non-zero unless this Noir table (lib/identity/src/table.nr, or"
        " a circuits release's handles-table.nr) is what this handles.json"
        " generates. Formatting is ignored, so no nargo is needed.",
    )
    parser.add_argument(
        "--compare-noir-tests",
        type=pathlib.Path,
        help="Likewise for the vector tests, lib/identity/src/table_tests.nr.",
    )
    args = parser.parse_args()

    if not SOURCE.exists():
        print(f"ERROR: {SOURCE} is missing", file=sys.stderr)
        return 1
    # Explicit encoding: handles.json holds non-ASCII, and the ambient locale
    # decides otherwise on a machine configured differently.
    raw = SOURCE.read_bytes()
    spec = json.loads(raw.decode("utf-8"))
    check_tags(spec)
    check_nodes(spec)
    digest = table_sha256(raw)

    compared = [
        (path, gen)
        for path, gen in ((args.compare_noir, gen_noir), (args.compare_noir_tests, gen_noir_tests))
        if path is not None
    ]
    if compared:
        for path, gen in compared:
            if noir_shape(path.read_text(encoding="utf-8")) != noir_shape(gen(spec, digest)):
                print(
                    f"ERROR: {path} is not the Noir this handles.json generates;"
                    " the circuits were built from another table, or the file was edited by hand",
                    file=sys.stderr,
                )
                return 1
            print(f"{path} matches handles.json {digest}")
        return 0

    outputs = [
        (SOL_OUT, sol_formatted(gen_sol(spec, digest))),
        (SOL_VECTORS_OUT, sol_formatted(gen_sol_vectors(spec, digest))),
        (RUST_OUT, gen_rust(spec, digest)),
        (TS_OUT, gen_ts(spec, digest)),
    ]
    if args.noir_out is not None:
        table = args.noir_out.resolve()
        outputs.append((table, noir_formatted(gen_noir(spec, digest))))
        outputs.append((table.with_name("table_tests.nr"), noir_formatted(gen_noir_tests(spec, digest))))

    if args.check:
        stale = [
            path
            for path, text in outputs
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if stale:
            print("ERROR: generated files are out of date. Run scripts/regen-identity-handles.py", file=sys.stderr)
            for path in stale:
                print(f"  {display(path)}", file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0

    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {display(path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
