#!/usr/bin/env python3
"""Regenerate the ceremony profile constants for every language.

`solidity/contracts/ceremony/profiles.json` is the single source of truth. Edit
it, then run this script. Up to three files are written and never drift apart:

    solidity/contracts/ceremony/CeremonyProfile.sol   # Solidity constants
    rust/profiles/src/profiles.rs                     # Rust constants
    ts/packages/contracts/src/ceremony/profiles.ts    # TypeScript constants

An output is skipped with a note until its target directory appears. The
Platform Verifiers are hand written in Solidity and READ these constants, the
way `HandleNormalizer` reads `HandleVectors`. Only the values come from here.
That is the point: four components must produce the same bytes, and a
disagreement between them is silent -- a Consumer dispatching on one string and
a verifier registered under another simply never meet.

`--check` additionally refuses a SHIPPED profile whose values changed while its
`ceremonyVersion` stayed put. Changing what a deployed verifier accepts is a new
version, not an edit, and the previous release is what says which is which.

Run: ./scripts/regen-ceremony-profiles.py
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import subprocess
import sys
import textwrap
from typing import Any

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SOLIDITY_ROOT = REPO_ROOT / "solidity"
SOURCE = SOLIDITY_ROOT / "contracts" / "ceremony" / "profiles.json"
SOURCE_REL = SOURCE.relative_to(REPO_ROOT).as_posix()

SOL_OUT = SOLIDITY_ROOT / "contracts" / "ceremony" / "CeremonyProfile.sol"
RUST_OUT = REPO_ROOT / "rust" / "profiles" / "src" / "profiles.rs"
TS_OUT = REPO_ROOT / "ts" / "packages" / "contracts" / "src" / "ceremony" / "profiles.ts"

BANNER = [
    "Generated by scripts/regen-ceremony-profiles.py. Do not edit.",
    f"The source of truth is {SOURCE_REL}.",
]

SESSIONS = ("token", "identity")


def header(comment: str) -> str:
    return "".join(f"{comment} {line}\n" for line in BANNER)


def as_lines(note: Any, width: int = 68) -> list[str]:
    """A note from the source file as comment lines."""
    if not note:
        return []
    if isinstance(note, list):
        return [str(line) for line in note]
    return textwrap.wrap(str(note), width=width)


def upper(name: str) -> str:
    """A platform or session name as a constant name fragment."""
    return name.upper().replace("-", "_")


def authority_name(host: str) -> str:
    """The constant suffix for an authority, read outside-in.

    `api.x.com` is `X_API` and `api.github.com` is `GITHUB_API`: drop the
    top-level label, then reverse. Reading the domain the way it nests keeps
    one platform's authorities adjacent when they are sorted, and it is
    derived rather than named, so a host and its constant cannot disagree.
    """
    labels = host.split(".")
    if len(labels) < 2:
        raise SystemExit(f"ERROR: authority {host!r} has no top-level label")
    return "_".join(label.upper().replace("-", "_") for label in reversed(labels[:-1]))


def request_line(session: dict[str, Any]) -> str:
    """The request-line prefix a Platform Verifier compares byte for byte.

    The trailing space is load-bearing: without it `GET /user ` would prefix
    `GET /users/me`, and one profile's path would answer for another's.
    """
    return f"{session['method']} {session['path']} "


def sessions_of(profile: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    """The profile's sessions in a fixed order, skipping those it has none of."""
    return [(name, profile["sessions"][name]) for name in SESSIONS if name in profile["sessions"]]


def authorities(spec: dict[str, Any]) -> list[tuple[str, str]]:
    """Every distinct authority as (constant suffix, host), in first-seen order."""
    out: list[tuple[str, str]] = []
    for profile in spec["profiles"]:
        for _, session in sessions_of(profile):
            entry = (authority_name(session["authority"]), session["authority"])
            if entry not in out:
                out.append(entry)
    clashes = {name for name, _ in out}
    if len(clashes) != len(out):
        raise SystemExit("ERROR: two different authorities share one constant name")
    return out


SAFE = re.compile(r"^[A-Za-z0-9._~:/?#\[\]@!$&*+,;=%-]+$")


def safe(value: str, what: str) -> str:
    """A value the three languages can all carry as a literal.

    The handles generator escapes instead, because its vectors deliberately
    hold bytes a source file cannot: that is what they test. Nothing here is
    like that. A path, a method, a host and a JSON member name are drawn from
    URL and identifier characters, so a quote or a backslash is a mistake, and
    escaping one would emit a constant no verifier could ever match. Refusing
    says so where the reason is visible -- rather than, as Solidity did before
    this check, as a parser error about an unexpected token.
    """
    if not SAFE.fullmatch(value):
        raise SystemExit(f"ERROR: {what} {value!r} carries a character a literal cannot hold")
    return value


def validate(spec: dict[str, Any]) -> None:
    """Refuse a spec that would generate constants nothing can rely on."""
    seen: set[str] = set()
    for profile in spec["profiles"]:
        platform = profile["platform"]
        if platform in seen:
            raise SystemExit(f"ERROR: {platform!r} appears twice")
        seen.add(platform)
        if not platform.islower() or not platform.isascii():
            raise SystemExit(f"ERROR: platform {platform!r} must be lowercase ASCII")
        safe(platform, "platform")
        for name, session in sessions_of(profile):
            host = safe(session["authority"], "authority")
            safe(session["method"], "method")
            safe(session["path"], "path")
            if name == "token" and session["secretField"] is not None:
                safe(session["secretField"], "secretField")
            if name == "identity":
                safe(session["idField"], "idField")
                safe(session["handleField"], "handleField")
            if host != host.lower() or host.endswith("."):
                raise SystemExit(
                    f"ERROR: authority {host!r} must be lowercase with no trailing dot"
                )
            if not session["path"].startswith("/"):
                raise SystemExit(f"ERROR: path {session['path']!r} must be absolute")
            if name == "identity":
                shape = session["idShape"]
                if shape not in ("jsonString", "jsonInteger"):
                    raise SystemExit(f"ERROR: unknown idShape {shape!r}")
        # A profile notarizing one session cannot be right: the bearer of the
        # token session is what the identity session spends, and the circuit
        # links them.
        if len(sessions_of(profile)) == 1:
            raise SystemExit(f"ERROR: {platform!r} has one session; expected none or both")


# --------------------------------------------------------------------------
# Version guard
# --------------------------------------------------------------------------


def without_notes(value: Any) -> Any:
    """The value with every `note` removed, so prose can change freely."""
    if isinstance(value, dict):
        return {k: without_notes(v) for k, v in value.items() if k != "note"}
    if isinstance(value, list):
        return [without_notes(v) for v in value]
    return value


def previous_release(spec: dict[str, Any]) -> tuple[str, dict[str, Any]] | None:
    """The newest release tag that carried this file, and what it said.

    Returns nothing when the file is new, when no release carries it yet, or
    when git is unavailable -- a check that cannot read history must not
    invent a verdict.
    """
    if shutil.which("git") is None:
        return None
    try:
        tags = subprocess.run(
            ["git", "tag", "--list", "v*", "--sort=-v:refname"],
            capture_output=True,
            text=True,
            check=True,
            cwd=REPO_ROOT,
        ).stdout.split()
    except subprocess.CalledProcessError:
        return None

    for tag in tags:
        done = subprocess.run(
            ["git", "show", f"{tag}:{SOURCE_REL}"],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
        )
        if done.returncode == 0:
            try:
                return tag, json.loads(done.stdout)
            except json.JSONDecodeError:
                return None
    return None


def check_versions(spec: dict[str, Any]) -> list[str]:
    """Complaints about profiles that changed without moving their version."""
    found = previous_release(spec)
    if found is None:
        return []
    tag, old = found

    released = {p["platform"]: p for p in old["profiles"]}
    problems = []
    for profile in spec["profiles"]:
        before = released.get(profile["platform"])
        if before is None:
            continue
        if without_notes(before) == without_notes(profile):
            continue
        if before["ceremonyVersion"] == profile["ceremonyVersion"]:
            problems.append(
                f"{profile['platform']}/v{profile['ceremonyVersion']} changed since {tag} "
                f"but kept its ceremonyVersion. Changing what a deployed verifier "
                f"accepts is a new version, not an edit."
            )
    return problems


# --------------------------------------------------------------------------
# Solidity
# --------------------------------------------------------------------------


def sol_doc(note: Any, indent: str = "    ") -> list[str]:
    lines = as_lines(note)
    if not lines:
        return []
    out = [f"{indent}/// @dev {lines[0]}"]
    out += [f"{indent}///      {line}" if line else f"{indent}///" for line in lines[1:]]
    return out


def gen_sol(spec: dict[str, Any]) -> str:
    profiles = spec["profiles"]
    versions = {p["ceremonyVersion"] for p in profiles}
    if len(versions) != 1:
        raise SystemExit("ERROR: the Solidity LAUNCH_VERSION assumes one version for all profiles")
    launch_version = versions.pop()

    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.24;",
        "",
        header("//").rstrip("\n"),
        "",
        "/// @title CeremonyProfile",
        "/// @notice The tags a Platform Verifier pins, and the governance-owned",
        "///         protocol parameters it reads.",
        "///",
    ]
    lines += [f"/// {line}" if line else "///" for line in as_lines(spec.get("note"), width=70)]
    lines += [
        "library CeremonyProfile {",
        "    // --- Platform identifiers -----------------------------------------------",
        "",
    ]
    for profile in profiles:
        name = upper(profile["platform"])
        lines.append(
            f'    bytes32 internal constant PLATFORM_{name} = keccak256(bytes("{profile["platform"]}"));'
        )

    lines += [
        "",
        "    // --- Authorities --------------------------------------------------------",
        "",
        "    /// @dev The lowercase ASCII TLS server name, with no trailing dot, that the",
        "    ///      notary authenticated. It reaches the verifier as `authorityId` and",
        "    ///      never as a transcript range: the transcript holds the authority",
        "    ///      only in a prover-composed `Host` header, which says nothing about",
        "    ///      which server answered (REQ-COMMON-21, REQ-COMMON-21A).",
        "",
    ]
    for suffix, host in authorities(spec):
        lines.append(
            f'    bytes32 internal constant AUTHORITY_{suffix} = keccak256(bytes("{host}"));'
        )

    lines += [
        "",
        "    // --- Sessions -------------------------------------------------------------",
        "",
        "    /// @dev The request-line prefix each session sends, trailing space included.",
        "    ///      The space is load-bearing: without it `GET /user ` would prefix",
        "    ///      `GET /users/me`, and one profile's path would answer for another's.",
        "",
    ]
    for profile in profiles:
        name = upper(profile["platform"])
        for session_name, session in sessions_of(profile):
            const = f"{name}_{upper(session_name)}_REQUEST_LINE"
            lines.append(f'    bytes internal constant {const} = "{request_line(session)}";')

    lines += [
        "",
        "    /// @dev How many committed ranges the token request carries. A confidential",
        "    ///      client commits its secret and a public client hides nothing, so this",
        "    ///      is one or zero and never a preference.",
        "",
    ]
    for profile in profiles:
        token = profile["sessions"].get("token")
        if token is None:
            continue
        count = 0 if token["secretField"] is None else 1
        lines.append(
            f"    uint256 internal constant {upper(profile['platform'])}_TOKEN_SENT_COMMITMENTS = {count};"
        )

    lines += [
        "",
        "    /// @dev The two identity members a Platform Verifier reads out of the",
        "    ///      revealed response bytes (REQ-PLAT-51).",
        "",
    ]
    for profile in profiles:
        identity = profile["sessions"].get("identity")
        if identity is None:
            continue
        name = upper(profile["platform"])
        lines.append(f'    string internal constant {name}_ID_FIELD = "{identity["idField"]}";')
        lines.append(
            f'    string internal constant {name}_HANDLE_FIELD = "{identity["handleField"]}";'
        )

    lines += [
        "",
        "    // --- Launch profile shape ------------------------------------------------",
        "",
        "    /// @dev Launch profiles are "
        + ", ".join(f"`{p['platform']}/v{p['ceremonyVersion']}`" for p in profiles)
        + "",
        "    ///      (REQ-PLAT-01).",
        f"    uint16 internal constant LAUNCH_VERSION = {launch_version};",
        "",
        "    /// @dev Derived from the session list each profile fixes, never stated",
        "    ///      beside it (REQ-COMMON-41).",
        "    function attestationCount(bytes32 platformId) internal pure returns (uint8) {",
    ]
    by_count: dict[int, list[str]] = {}
    for profile in profiles:
        by_count.setdefault(len(sessions_of(profile)), []).append(upper(profile["platform"]))
    for count in sorted(by_count):
        test = " || ".join(f"platformId == PLATFORM_{name}" for name in by_count[count])
        lines.append(f"        if ({test}) return {count};")
    lines += [
        "        revert UnknownPlatform(platformId);",
        "    }",
        "",
        "    error UnknownPlatform(bytes32 platformId);",
        "",
        "    // --- Protocol parameters -------------------------------------------------",
        "",
    ]
    lines += sol_doc(spec["parameters"].get("note"))
    for profile in profiles:
        if "proofLifetimeSeconds" not in profile:
            continue
        lines.append(
            f"    uint64 internal constant LAUNCH_PROOF_LIFETIME_{upper(profile['platform'])} = "
            f"{profile['proofLifetimeSeconds']};"
        )
    lines.append(
        "    uint64 internal constant LAUNCH_MAX_FUTURE_ATTESTATION_SKEW = "
        f"{spec['parameters']['maxFutureAttestationSkewSeconds']};"
    )
    lines += ["}", ""]
    return "\n".join(lines)


def sol_formatted(source: str) -> str:
    """Run the repository's `forge fmt` over generated Solidity."""
    if shutil.which("forge") is None:
        print("ERROR: forge is required to format the generated Solidity", file=sys.stderr)
        raise SystemExit(1)
    done = subprocess.run(
        ["forge", "fmt", "--raw", "-"],
        input=source,
        capture_output=True,
        text=True,
        cwd=SOLIDITY_ROOT,
    )
    if done.returncode != 0:
        print(f"ERROR: forge fmt failed:\n{done.stderr}", file=sys.stderr)
        raise SystemExit(1)
    return done.stdout


# --------------------------------------------------------------------------
# Rust
# --------------------------------------------------------------------------


def rust_doc(note: Any, indent: str = "", marker: str = "///") -> list[str]:
    return [f"{indent}{marker} {line}" if line else f"{indent}{marker}" for line in as_lines(note)]


def rust_str(value: str | None) -> str:
    if value is None:
        return "None"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'Some("{escaped}")'


def rust_session(session: dict[str, Any], indent: int) -> list[str]:
    pad = " " * indent
    return [
        f"{pad}session: Session {{",
        f'{pad}    authority: "{session["authority"]}",',
        f'{pad}    method: "{session["method"]}",',
        f'{pad}    path: "{session["path"]}",',
        f'{pad}    request_line: "{request_line(session)}",',
        f"{pad}}},",
    ]


def gen_rust(spec: dict[str, Any]) -> str:
    lines = [header("//").rstrip("\n"), ""]
    lines += rust_doc(spec.get("note"), marker="//!")
    lines += [
        "",
        "/// Which shape a platform's immutable identifier takes in its response.",
        "///",
        "/// The bare-integer form takes its structural terminator with it, which is",
        "/// what proves the revealed digits are the whole number rather than a prefix",
        "/// of a longer one (REQ-PLAT-51).",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum IdShape {",
        "    /// `\"id\":\"2244994945\"`.",
        "    JsonString,",
        "    /// `\"id\":583231,`",
        "    JsonInteger,",
        "}",
        "",
        "/// One notarized session: which server, and which request.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct Session {",
        "    /// The lowercase TLS server name the notary authenticates, with no",
        "    /// trailing dot. `authorityId` is its keccak256, which the verifier",
        "    /// compares against the constant its profile pins (REQ-COMMON-21A). It is",
        "    /// also the `Host` header the request carries.",
        "    pub authority: &'static str,",
        "    pub method: &'static str,",
        "    pub path: &'static str,",
        "    /// The request-line prefix the verifier compares byte for byte, trailing",
        "    /// space included. The space is what stops `GET /user ` prefixing",
        "    /// `GET /users/me`.",
        "    pub request_line: &'static str,",
        "}",
        "",
        "/// The token session: the OAuth exchange.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct TokenSession {",
        "    pub session: Session,",
        "    /// The body field committed rather than revealed, ordered last so the",
        "    /// committed run is a suffix (REQ-COMMON-22). `None` for a public client,",
        "    /// whose request hides nothing and is revealed whole.",
        "    pub secret_field: Option<&'static str>,",
        "}",
        "",
        "/// The identity session: the authenticated read that names the account.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct IdentitySession {",
        "    pub session: Session,",
        "    pub id_field: &'static str,",
        "    pub id_shape: IdShape,",
        "    pub handle_field: &'static str,",
        "}",
        "",
        "/// One platform's ceremony profile at one Platform Ceremony Version.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct Profile {",
        "    /// The platform name. `platformId` is its keccak256.",
        "    pub platform: &'static str,",
        "    /// A profile is the pair, not the name (REQ-PLAT-01).",
        "    pub ceremony_version: u16,",
        "    /// `None` where the profile notarizes nothing.",
        "    pub token: Option<TokenSession>,",
        "    pub identity: Option<IdentitySession>,",
        "}",
        "",
        "impl Profile {",
        "    /// How many attestations a submission for this profile carries. Derived",
        "    /// from the sessions rather than stated beside them (REQ-COMMON-41).",
        "    pub const fn attestation_count(&self) -> u8 {",
        "        self.token.is_some() as u8 + self.identity.is_some() as u8",
        "    }",
        "}",
        "",
    ]

    for profile in spec["profiles"]:
        name = upper(profile["platform"])
        lines += rust_doc(profile.get("note"))
        lines.append(f"pub const {name}: Profile = Profile {{")
        lines.append(f'    platform: "{profile["platform"]}",')
        lines.append(f"    ceremony_version: {profile['ceremonyVersion']},")

        token = profile["sessions"].get("token")
        if token is None:
            lines.append("    token: None,")
        else:
            lines.append("    token: Some(TokenSession {")
            lines += rust_session(token, 8)
            lines.append(f"        secret_field: {rust_str(token['secretField'])},")
            lines.append("    }),")

        identity = profile["sessions"].get("identity")
        if identity is None:
            lines.append("    identity: None,")
        else:
            shape = "JsonString" if identity["idShape"] == "jsonString" else "JsonInteger"
            lines.append("    identity: Some(IdentitySession {")
            lines += rust_session(identity, 8)
            lines.append(f'        id_field: "{identity["idField"]}",')
            lines.append(f"        id_shape: IdShape::{shape},")
            lines.append(f'        handle_field: "{identity["handleField"]}",')
            lines.append("    }),")
        lines += ["};", ""]

    names = ", ".join(f"&{upper(p['platform'])}" for p in spec["profiles"])
    lines += [
        "/// The closed launch list. A platform outside it has no profile, and",
        "/// `CeremonyProfile.attestationCount` reverts on one.",
        f"pub const LAUNCH: &[&Profile] = &[{names}];",
        "",
        "/// The launch profile for a platform name, or nothing.",
        "///",
        "/// Nothing, rather than a default: a caller that cannot name the platform has",
        "/// nothing to notarize, and guessing produces evidence no verifier accepts.",
        "pub fn launch(platform: &str) -> Option<&'static Profile> {",
        "    LAUNCH.iter().copied().find(|p| p.platform == platform)",
        "}",
        "",
        "/// Governance-owned launch parameters, in seconds.",
        f"pub const MAX_FUTURE_ATTESTATION_SKEW_SECONDS: u64 = "
        f"{spec['parameters']['maxFutureAttestationSkewSeconds']};",
    ]
    for profile in spec["profiles"]:
        if "proofLifetimeSeconds" not in profile:
            continue
        lines.append(
            f"pub const PROOF_LIFETIME_SECONDS_{upper(profile['platform'])}: u64 = "
            f"{profile['proofLifetimeSeconds']};"
        )
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# TypeScript
# --------------------------------------------------------------------------


def ts_str(value: str | None) -> str:
    if value is None:
        return "null"
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def ts_doc(note: Any, indent: str = "") -> list[str]:
    lines = as_lines(note)
    if not lines:
        return []
    out = [f"{indent}/**"]
    out += [f"{indent} * {line}" if line else f"{indent} *" for line in lines]
    out.append(f"{indent} */")
    return out


def ts_session(session: dict[str, Any], indent: int) -> list[str]:
    pad = " " * indent
    return [
        f"{pad}session: {{",
        f'{pad}  authority: {ts_str(session["authority"])},',
        f'{pad}  method: {ts_str(session["method"])},',
        f'{pad}  path: {ts_str(session["path"])},',
        f"{pad}  requestLine: {ts_str(request_line(session))},",
        f"{pad}}},",
    ]


def gen_ts(spec: dict[str, Any]) -> str:
    lines = [header("//").rstrip("\n"), ""]
    lines += ts_doc(spec.get("note"))
    lines += [
        "",
        "/** Which shape a platform's immutable identifier takes in its response. */",
        "export type IdShape = 'jsonString' | 'jsonInteger'",
        "",
        "export interface Session {",
        "  /** The lowercase TLS server name the notary authenticates. */",
        "  readonly authority: string",
        "  readonly method: string",
        "  readonly path: string",
        "  /** The request-line prefix the verifier compares byte for byte. */",
        "  readonly requestLine: string",
        "}",
        "",
        "export interface TokenSession {",
        "  readonly session: Session",
        "  /** The body field committed rather than revealed, or null. */",
        "  readonly secretField: string | null",
        "}",
        "",
        "export interface IdentitySession {",
        "  readonly session: Session",
        "  readonly idField: string",
        "  readonly idShape: IdShape",
        "  readonly handleField: string",
        "}",
        "",
        "export interface Profile {",
        "  /** The platform name. The platform id is its keccak256. */",
        "  readonly platform: string",
        "  readonly ceremonyVersion: number",
        "  readonly token: TokenSession | null",
        "  readonly identity: IdentitySession | null",
        "}",
        "",
    ]

    for profile in spec["profiles"]:
        name = upper(profile["platform"])
        lines += ts_doc(profile.get("note"))
        lines.append(f"export const {name}: Profile = {{")
        lines.append(f"  platform: {ts_str(profile['platform'])},")
        lines.append(f"  ceremonyVersion: {profile['ceremonyVersion']},")

        token = profile["sessions"].get("token")
        if token is None:
            lines.append("  token: null,")
        else:
            lines.append("  token: {")
            lines += ts_session(token, 4)
            lines.append(f"    secretField: {ts_str(token['secretField'])},")
            lines.append("  },")

        identity = profile["sessions"].get("identity")
        if identity is None:
            lines.append("  identity: null,")
        else:
            lines.append("  identity: {")
            lines += ts_session(identity, 4)
            lines.append(f"    idField: {ts_str(identity['idField'])},")
            lines.append(f"    idShape: {ts_str(identity['idShape'])},")
            lines.append(f"    handleField: {ts_str(identity['handleField'])},")
            lines.append("  },")
        lines += ["}", ""]

    names = ", ".join(upper(p["platform"]) for p in spec["profiles"])
    lines += [
        "/** The closed launch list. */",
        f"export const LAUNCH: readonly Profile[] = [{names}]",
        "",
        "/** The launch profile for a platform name, or undefined. */",
        "export function launch(platform: string): Profile | undefined {",
        "  return LAUNCH.find((p) => p.platform === platform)",
        "}",
        "",
        "/** How many attestations a submission for this profile carries. */",
        "export function attestationCount(profile: Profile): number {",
        "  return (profile.token ? 1 : 0) + (profile.identity ? 1 : 0)",
        "}",
        "",
        "/** Governance-owned launch parameters, in seconds. */",
        f"export const MAX_FUTURE_ATTESTATION_SKEW_SECONDS = "
        f"{spec['parameters']['maxFutureAttestationSkewSeconds']}",
    ]
    for profile in spec["profiles"]:
        if "proofLifetimeSeconds" not in profile:
            continue
        lines.append(
            f"export const PROOF_LIFETIME_SECONDS_{upper(profile['platform'])} = "
            f"{profile['proofLifetimeSeconds']}"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Write nothing; exit non-zero if a generated file is stale or a "
        "shipped profile changed without moving its version.",
    )
    args = parser.parse_args()

    if not SOURCE.exists():
        print(f"ERROR: {SOURCE} is missing", file=sys.stderr)
        return 1
    spec = json.loads(SOURCE.read_text(encoding="utf-8"))
    validate(spec)

    outputs = [(SOL_OUT, sol_formatted(gen_sol(spec)))]
    skipped = []
    for path, gen in ((RUST_OUT, gen_rust), (TS_OUT, gen_ts)):
        if path.parent.exists():
            outputs.append((path, gen(spec)))
        else:
            skipped.append(path)

    for path in skipped:
        print(
            f"note: skipping {path.relative_to(REPO_ROOT)} — "
            f"{path.parent.relative_to(REPO_ROOT)} does not exist yet"
        )

    if args.check:
        failed = False
        for problem in check_versions(spec):
            print(f"ERROR: {problem}", file=sys.stderr)
            failed = True
        stale = [
            path
            for path, text in outputs
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if stale:
            print(
                "ERROR: generated files are out of date. Run scripts/regen-ceremony-profiles.py",
                file=sys.stderr,
            )
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            failed = True
        if failed:
            return 1
        print("generated files are up to date")
        return 0

    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
