#!/usr/bin/env python3
"""Regenerate the identity platform constants and the handle vector table.

`solidity/contracts/identity/handles.json` is the single source of truth. Edit
it, then run this script. Up to three files are written and never drift apart:

    solidity/contracts/identity/HandleVectors.sol          # Solidity constants + vectors
    rust/identity/src/handle_vectors.rs                    # Rust constants + vectors
    ts/packages/contracts/src/identity/handleVectors.ts    # TypeScript constants + vectors

The Rust package does not exist in this repo yet; an output is skipped with a
note until its target directory appears. The normalizer
itself is hand written in each language. Only the constants and the vectors
come from here. That is the point: several implementations, one vector table,
so a difference between them fails a test instead of writing a different key
on chain.

Run: ./scripts/regen-identity-handles.py
"""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import textwrap
import sys
from typing import Any

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SOLIDITY_ROOT = REPO_ROOT / "solidity"
SOURCE = SOLIDITY_ROOT / "contracts" / "identity" / "handles.json"

SOL_OUT = SOLIDITY_ROOT / "contracts" / "identity" / "HandleVectors.sol"
# An output is skipped (with a note) while its parent directory is absent, so
# `--check` holds only the outputs that exist to account. The TypeScript
# package is live; the Rust one is not in this repo yet.
RUST_OUT = REPO_ROOT / "rust" / "identity" / "src" / "handle_vectors.rs"
TS_OUT = REPO_ROOT / "ts" / "packages" / "contracts" / "src" / "identity" / "handleVectors.ts"

BANNER = [
    "Generated by scripts/regen-identity-handles.py. Do not edit.",
    "The source of truth is solidity/contracts/identity/handles.json.",
]


def header(comment: str) -> str:
    return "".join(f"{comment} {line}\n" for line in BANNER)


def as_lines(note: Any) -> list[str]:
    """A note from handles.json as comment lines.

    The file writes a note either as one string or as a list of lines, and both
    spellings appear in it already.
    """
    if not note:
        return []
    if isinstance(note, list):
        return [str(line) for line in note]
    return textwrap.wrap(str(note), width=68)


def rule_flags(platform: dict[str, Any]) -> tuple[tuple[str, bool, str], ...]:
    """The normalizer's boolean rules for one platform, as (name, value, doc).

    Every language reads this, so a flag added here reaches all three outputs
    at once. Restating the list per generator is the drift this file exists to
    prevent.
    """
    return (
        ("STRIP_LEADING_AT", bool(platform.get("stripLeadingAt", False)),
         "Remove one leading `@`."),
        ("IS_EMAIL", platform.get("shape") == "email",
         "Validate as an address instead of a bare handle."),
        ("ALLOW_UNDERSCORE", bool(platform.get("allowUnderscore", False)),
         "Allow `_`."),
        ("ALLOW_HYPHEN", bool(platform.get("allowHyphen", False)),
         "Allow `-`, but not leading, trailing or doubled."),
    )


def sol_escape(value: str) -> str:
    """Solidity string literal. Escape the bytes a source file cannot hold."""
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            # Solidity has no \u escape in a plain string, so emit the UTF-8
            # bytes one at a time. A vector that carries a non-ASCII byte is
            # there to prove the normalizer refuses it.
            out.extend(f"\\x{b:02x}" for b in ch.encode("utf-8"))
        else:
            out.append(ch)
    return "".join(out)


def rust_escape(value: str) -> str:
    """Rust string literal.

    Rust writes a code point as `\\u{e9}`, not as JSON's `\\u00e9`, so the
    escapes cannot be borrowed from `json.dumps` unchanged.
    """
    out = []
    for ch in value:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return "".join(out)


def error_index(errors: list[dict[str, Any]], key: str) -> int:
    for i, err in enumerate(errors):
        if err["key"] == key:
            return i
    raise SystemExit(f"ERROR: unknown error kind {key!r} in a vector")


def gen_sol(spec: dict[str, Any]) -> str:
    platforms = spec["platforms"]
    errors = spec["errors"]
    vectors = spec["vectors"]

    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.20;",
        "",
        header("//").rstrip("\n"),
        "",
        'import {HandleNormalizer} from "./HandleNormalizer.sol";',
        "",
        "/// @notice Platform ids and the shared handle vector table.",
        "///",
        "/// @dev The vectors are here rather than in the test file because Rust and",
        "///      TypeScript run the same table. A normalizer that disagrees with",
        "///      another language fails a test instead of writing a different key.",
        "library HandleVectors {",
    ]

    for p in platforms:
        name = p["key"].upper()
        lines.append(f'    /// keccak256(bytes("{p["domain"]}"))')
        lines.append(
            f"    bytes32 internal constant PLATFORM_{name} ="
            f' keccak256(bytes("{p["domain"]}"));'
        )
    lines.append("")

    for p in platforms:
        name = p["key"].upper()
        lines.append(
            f"    uint256 internal constant MAX_LENGTH_{name} = {p['maxLength']};"
        )
    lines.append("")

    lines.append(
        "    /// The normalizer rules for a platform, as `handles.json` states"
    )
    lines.append("    /// them.")
    lines.append("    ///")
    lines.append(
        "    /// @dev Generated so a deploy, a test and a consumer cannot each"
    )
    lines.append(
        "    ///      keep their own copy. Reverts on an unknown platform rather"
    )
    lines.append(
        "    ///      than returning a permissive default, because a wrong rule"
    )
    lines.append("    ///      set writes wrong keys.")
    lines.append(
        "    function rulesFor(bytes32 platformId) internal pure"
        " returns (HandleNormalizer.Rules memory) {"
    )
    for p in platforms:
        name = p["key"].upper()
        is_email = str(p.get("shape") == "email").lower()
        lines.append(f"        if (platformId == PLATFORM_{name}) {{")
        lines.append("            return HandleNormalizer.Rules({")
        lines.append(f"                maxLength: {p['maxLength']},")
        lines.append(
            f"                stripLeadingAt: {str(p.get('stripLeadingAt', False)).lower()},"
        )
        lines.append(f"                isEmail: {is_email},")
        lines.append(
            f"                allowUnderscore: {str(p.get('allowUnderscore', False)).lower()},"
        )
        lines.append(
            f"                allowHyphen: {str(p.get('allowHyphen', False)).lower()}"
        )
        lines.append("            });")
        lines.append("        }")
    lines.append('        revert("unknown platform");')
    lines.append("    }")
    lines.append("")

    lines.append(
        "    /// How far ahead of the chain this platform's observations may be"
    )
    lines.append("    /// dated, in seconds.")
    lines.append("    ///")
    lines.append(
        "    /// @dev `IdentityNames` supersedes a binding only on a strictly newer"
    )
    lines.append(
        "    ///      `observedAt`, so an allowance too generous lets a proof dated"
    )
    lines.append(
        "    ///      ahead hold a name until the clock catches up — and proving"
    )
    lines.append(
        "    ///      again is the whole remedy the design relies on. Unknown"
    )
    lines.append("    ///      platforms revert, like `rulesFor`.")
    lines.append(
        "    function futureAllowanceFor(bytes32 platformId) internal pure"
        " returns (uint64) {"
    )
    for p_ in platforms:
        name = p_["key"].upper()
        for line in as_lines(p_.get("allowanceNote", "")):
            lines.append(f"        // {line}")
        lines.append(
            f"        if (platformId == PLATFORM_{name})"
            f" return {p_['futureAllowanceSeconds']};"
        )
    lines.append('        revert("unknown platform");')
    lines.append("    }")
    lines.append("")

    lines.append("    /// One case from the shared table.")
    lines.append("    struct Vector {")
    lines.append("        string platform;")
    lines.append("        string input;")
    lines.append("        string output;")
    lines.append("        bool accepted;")
    lines.append("        uint8 errorKind;")
    lines.append("    }")
    lines.append("")

    for i, err in enumerate(errors):
        lines.append(f"    uint8 internal constant ERROR_{err['key'].upper()} = {i};")
    lines.append("")

    lines.append(f"    uint256 internal constant COUNT = {len(vectors)};")
    lines.append("")
    lines.append("    function all() internal pure returns (Vector[] memory v) {")
    lines.append(f"        v = new Vector[]({len(vectors)});")
    for i, vec in enumerate(vectors):
        accepted = "output" in vec
        out = sol_escape(vec.get("output", ""))
        kind = "0" if accepted else str(error_index(errors, vec["error"]))
        lines.append(
            f'        v[{i}] = Vector("{vec["platform"]}", "{sol_escape(vec["input"])}",'
            f' "{out}", {"true" if accepted else "false"}, {kind});'
        )
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_rust(spec: dict[str, Any]) -> str:
    platforms = spec["platforms"]
    errors = spec["errors"]
    vectors = spec["vectors"]

    lines = [
        header("//").rstrip("\n"),
        "",
        "//! Platform ids and the shared handle vector table.",
        "",
        "/// One case from the shared table.",
        "pub struct Vector {",
        "    /// Platform key, as written in the source table.",
        "    pub platform: &'static str,",
        "    /// The handle exactly as a caller supplied it.",
        "    pub input: &'static str,",
        "    /// The normalized handle, or an empty string when the case is refused.",
        "    pub output: &'static str,",
        "    /// Whether the transform accepts this case.",
        "    pub accepted: bool,",
        "    /// Which refusal the case expects, when it is refused.",
        "    pub error_kind: u8,",
        "}",
        "",
    ]

    for p in platforms:
        lines.append("/// keccak256 of this string is the platform id.")
        lines.append(
            f'pub const PLATFORM_{p["key"].upper()}_DOMAIN: &str = "{p["domain"]}";'
        )
    lines.append("")

    for p in platforms:
        lines.append(f"/// Bytes a {p['key']} handle may have after normalization.")
        lines.append(
            f"pub const MAX_LENGTH_{p['key'].upper()}: usize = {p['maxLength']};"
        )
    lines.append("")

    # The normalizer's rules, generated rather than restated. A deploy writes
    # these on chain, so a Rust copy that drifted from the Solidity one would
    # key every handle on that platform differently.
    for p in platforms:
        name = p["key"].upper()
        for flag, value, doc in rule_flags(p):
            lines.append(f"/// {doc}")
            lines.append(
                f"pub const {flag}_{name}: bool = {'true' if value else 'false'};"
            )
    lines.append("")

    for p in platforms:
        for line in as_lines(p.get("allowanceNote", "")):
            lines.append(f"/// {line}")
        lines.append(
            f"pub const FUTURE_ALLOWANCE_{p['key'].upper()}: u64 ="
            f" {p['futureAllowanceSeconds']};"
        )
    lines.append("")

    for i, err in enumerate(errors):
        lines.append(f"/// {err['note']}")
        lines.append(f"pub const ERROR_{err['key'].upper()}: u8 = {i};")
    lines.append("")

    lines.append("/// Every case, shared with Solidity and TypeScript.")
    lines.append(f"pub const VECTORS: [Vector; {len(vectors)}] = [")
    for vec in vectors:
        accepted = "output" in vec
        out = rust_escape(vec.get("output", ""))
        kind = 0 if accepted else error_index(errors, vec["error"])
        lines.append("    Vector {")
        lines.append(f'        platform: "{vec["platform"]}",')
        lines.append(f'        input: "{rust_escape(vec["input"])}",')
        lines.append(f'        output: "{out}",')
        lines.append(f"        accepted: {'true' if accepted else 'false'},")
        lines.append(f"        error_kind: {kind},")
        lines.append("    },")
    lines.append("];")
    return "\n".join(lines) + "\n"


def gen_ts(spec: dict[str, Any]) -> str:
    platforms = spec["platforms"]
    errors = spec["errors"]
    vectors = spec["vectors"]

    lines = [
        header("//").rstrip("\n"),
        "",
        "/// Platform ids and the shared handle vector table.",
        "",
        "export interface HandleVector {",
        "  platform: string",
        "  input: string",
        "  /** The normalized handle, or an empty string when the case is refused. */",
        "  output: string",
        "  accepted: boolean",
        "  errorKind: number",
        "}",
        "",
    ]

    for p in platforms:
        lines.append(
            f"/** keccak256 of this string is the platform id. */"
        )
        lines.append(
            f"export const PLATFORM_{p['key'].upper()}_DOMAIN = '{p['domain']}'"
        )
    lines.append("")

    for p in platforms:
        lines.append(
            f"/** Bytes a {p['key']} handle may have after normalization. */"
        )
        lines.append(
            f"export const MAX_LENGTH_{p['key'].upper()} = {p['maxLength']}"
        )
    lines.append("")

    # The normalizer's rules, generated rather than restated, exactly as Rust
    # and Solidity take them. A hardcoded copy here would key a handle
    # differently from the chain that stores it, and the vector table catches
    # that only where a case happens to exercise the flag.
    for p in platforms:
        name = p["key"].upper()
        for flag, value, doc in rule_flags(p):
            lines.append(f"/** {doc} */")
            lines.append(
                f"export const {flag}_{name} = {'true' if value else 'false'}"
            )
    lines.append("")

    for p in platforms:
        for line in as_lines(p.get("allowanceNote", "")):
            lines.append(f"/// {line}")
        lines.append(
            f"export const FUTURE_ALLOWANCE_{p['key'].upper()} ="
            f" {p['futureAllowanceSeconds']}"
        )
    lines.append("")

    for i, err in enumerate(errors):
        lines.append(f"export const ERROR_{err['key'].upper()} = {i}")
    lines.append("")

    lines.append("export const HANDLE_VECTORS: HandleVector[] = [")
    for vec in vectors:
        accepted = "output" in vec
        out = json.dumps(vec.get("output", ""))
        kind = 0 if accepted else error_index(errors, vec["error"])
        lines.append(
            f"  {{ platform: {json.dumps(vec['platform'])},"
            f" input: {json.dumps(vec['input'])},"
            f" output: {out},"
            f" accepted: {'true' if accepted else 'false'},"
            f" errorKind: {kind} }},"
        )
    lines.append("]")
    return "\n".join(lines) + "\n"


def sol_formatted(text: str) -> str:
    """Run the emitted Solidity through `forge fmt`.

    Matching the formatter by hand is a losing game — it collapses a struct
    literal onto one line when it fits and splits it when it does not — and
    losing it means the committed file is never what this script produces, so
    `--check` can only ever be red. Formatting here makes the two the same
    thing.
    """
    forge = shutil.which("forge")
    if forge is None:
        print("ERROR: forge is not on PATH, so the Solidity cannot be formatted", file=sys.stderr)
        raise SystemExit(1)

    done = subprocess.run(
        [forge, "fmt", "--raw", "-"],
        input=text,
        capture_output=True,
        text=True,
        cwd=SOLIDITY_ROOT,
    )
    if done.returncode != 0:
        print(f"ERROR: forge fmt failed:\n{done.stderr}", file=sys.stderr)
        raise SystemExit(1)
    return done.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Write nothing; exit non-zero if any generated file is out of date.",
    )
    args = parser.parse_args()

    if not SOURCE.exists():
        print(f"ERROR: {SOURCE} is missing", file=sys.stderr)
        return 1
    # Explicit encoding: handles.json holds non-ASCII, and the ambient locale
    # decides otherwise on a machine configured differently.
    spec = json.loads(SOURCE.read_text(encoding="utf-8"))

    outputs = []
    skipped = []
    outputs.append((SOL_OUT, sol_formatted(gen_sol(spec))))
    # Emit an output only once its package directory exists. TS does; the Rust
    # package is not in this repo yet.
    for path, gen in ((RUST_OUT, gen_rust), (TS_OUT, gen_ts)):
        if path.parent.exists():
            outputs.append((path, gen(spec)))
        else:
            skipped.append(path)

    for path in skipped:
        print(
            f"note: skipping {path.relative_to(REPO_ROOT)} — "
            f"{path.parent.relative_to(REPO_ROOT)} does not exist yet"
        )

    if args.check:
        stale = [
            path
            for path, text in outputs
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if stale:
            print("ERROR: generated files are out of date. Run scripts/regen-identity-handles.py", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0

    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
