#!/usr/bin/env bash
# Vendor the ceremony circuits' UltraHonk verifiers from the pinned
# libid-circuits release into solidity/contracts/circuits/<Contract>.sol:
#
#   bearer-link-x       ->  BearerLinkXHonkVerifier.sol       (the x profile)
#   bearer-link-github  ->  BearerLinkGithubHonkVerifier.sol  (the github profile)
#   oidc-google  ->  OidcGoogleHonkVerifier.sol   (the google profile)
#
# The pin is solidity/contracts/circuits/circuits.json: the release version
# and each tarball's sha256. Downloads are checked against it, the release
# manifest is held to it, and each circuit's handles-table.nr must be what
# handles.json generates (`--compare-noir`). The sources are gitignored and
# vendored before every build. Last, it writes the committed
# CircuitCodehashes.sol, the runtime code hashes the Platform Verifiers pin.
#
# Moving the pin: write the new version and digests (from the release page)
# into circuits.json, run this script, commit circuits.json and
# CircuitCodehashes.sol.
#
# Usage:
#   scripts/vendor-circuit-verifiers.sh                    # write the verifiers from the pin
#   scripts/vendor-circuit-verifiers.sh --local <artifacts>
#
# --local takes the verifiers from a libid-circuits `scripts/build.sh --out
# <artifacts>` build, for development only; the written files say so.
#
# Requires curl, jq, tar, forge, cast, python3 and shasum or sha256sum.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOLIDITY="$REPO_ROOT/solidity"
DEST_REL="contracts/circuits"
DEST="$SOLIDITY/$DEST_REL"
PIN="$DEST/circuits.json"
CODEHASHES="CircuitCodehashes.sol"
RELEASES="https://github.com/libid-org/libID-circuits/releases/download"

LOCAL=""
if [[ "${1:-}" == "--local" ]]; then
    LOCAL="${2:?--local needs an artifacts directory}"
    shift 2
fi
if [[ $# -gt 0 ]]; then
    echo "unknown argument: $1" >&2
    exit 2
fi

for tool in curl jq tar forge cast; do
    command -v "$tool" >/dev/null || { echo "$tool is required" >&2; exit 1; }
done
sha256() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}

[[ -f "$PIN" ]] || { echo "no pin at $PIN" >&2; exit 1; }

# The pin's circuits, read once: each one's name, contract and tarball sha256
# ("null" until a release is pinned).
CIRCUITS=() CONTRACTS=() DIGESTS=()
while IFS=$'\t' read -r circuit contract digest; do
    CIRCUITS+=("$circuit") CONTRACTS+=("$contract") DIGESTS+=("$digest")
done < <(jq -r '.circuits | to_entries[] | "\(.key)\t\(.value.contract)\t\(.value.sha256)"' "$PIN")

# The circuit in `$1` was compiled from this repository's handle table.
require_table() {
    local dir="$1" circuit="$2"
    [[ -f "$dir/handles-table.nr" ]] ||
        { echo "$circuit: no handles-table.nr; it predates the shipped handle table, or the build is not libid-circuits'" >&2; exit 1; }
    python3 "$REPO_ROOT/scripts/regen-identity-handles.py" --compare-noir "$dir/handles-table.nr" >/dev/null || {
        echo "$circuit was built from another handle table than contracts/handles/handles.json" >&2
        echo "  regenerate: scripts/regen-identity-handles.py --noir-out <libid-circuits>/lib/identity/src/table.nr, then rebuild" >&2
        exit 1
    }
}

# The interchange-format checks and the formatting, shared by both modes.
write_verifier() {
    local src="$1" contract="$2" banner="$3" contracts
    [[ -f "$src" ]] || { echo "no $contract.sol at $src" >&2; exit 1; }
    contracts="$(grep -c '^contract ' "$src" || true)"
    [[ "$contracts" == 1 ]] ||
        { echo "$contract.sol: expected one contract, found $contracts" >&2; exit 1; }
    grep -q "^contract $contract is IVerifier" "$src" ||
        { echo "$contract.sol: its contract is not '$contract is IVerifier'" >&2; exit 1; }
    if grep -q '^library ' "$src"; then
        echo "$contract.sol: declares a library; the crate deploys verifiers unlinked" >&2
        exit 1
    fi
    awk -v banner="$banner" '
        !done && /^pragma / { print banner; done = 1 }
        { print }
    ' "$src" | (cd "$SOLIDITY" && forge fmt --raw - | forge fmt --raw -) > "$STAGE/$contract.sol"
}

# Write the runtime code hash (EXTCODEHASH) of each verifier just written.
# Only the verifiers are compiled, so a stale constants file cannot block it.
write_codehashes() {
    local origin="$1" out="$DEST/$CODEHASHES" i name hash
    local -a sources=()
    for i in "${!CIRCUITS[@]}"; do
        sources+=("$DEST_REL/${CONTRACTS[$i]}.sol")
    done
    (cd "$SOLIDITY" && forge build "${sources[@]}" >/dev/null)
    {
        echo "// SPDX-License-Identifier: MIT"
        echo "pragma solidity ^0.8.24;"
        echo
        echo "// Generated by scripts/vendor-circuit-verifiers.sh from $origin. Do not edit."
        echo
        echo "/// @notice The runtime code hash of each circuit's vendored Honk verifier: what"
        echo "///         EXTCODEHASH reports at any deployed copy. A Platform Verifier pins"
        echo "///         its own circuit's and refuses every other verifier."
        echo "library CircuitCodehashes {"
        for i in "${!CIRCUITS[@]}"; do
            name="$(tr 'a-z-' 'A-Z_' <<< "${CIRCUITS[$i]}")"
            hash="$(jq -r '.deployedBytecode.object' "$SOLIDITY/out/${CONTRACTS[$i]}.sol/${CONTRACTS[$i]}.json" | cast keccak)"
            echo "    /// \`${CONTRACTS[$i]}\`, the \`${CIRCUITS[$i]}\` circuit's verifier."
            echo "    bytes32 internal constant $name = $hash;"
        done
        echo "}"
    } | (cd "$SOLIDITY" && forge fmt --raw -) > "$out"
    echo "==> runtime code hashes -> $DEST_REL/$CODEHASHES"
}

if [[ -n "$LOCAL" ]]; then
    LOCAL="$(cd "$LOCAL" && pwd)"
    STAGE="$(mktemp -d)"
    trap 'rm -rf "$STAGE"' EXIT
    # The libid-circuits commit, if the build left one; never the local path.
    origin="a local libid-circuits build"
    if [[ -f "$LOCAL/commit" ]]; then
        commit="$(tr -cd '0-9a-f' < "$LOCAL/commit" | head -c 40)"
        [[ -n "$commit" ]] && origin="a local libid-circuits build of commit $commit"
    fi
    for i in "${!CIRCUITS[@]}"; do
        circuit="${CIRCUITS[$i]}" contract="${CONTRACTS[$i]}"
        require_table "$LOCAL/$circuit" "$circuit"
        write_verifier "$LOCAL/$circuit/$contract.sol" "$contract" \
            "// UNRELEASED: $circuit, from $origin, by scripts/vendor-circuit-verifiers.sh --local.\n// Not pinned by circuits.json. Develop against it; never deploy it."
        echo "==> $circuit -> $DEST_REL/$contract.sol (local, unpinned)"
    done
    cp "$STAGE"/*.sol "$DEST/"
    write_codehashes "$origin (unreleased, unpinned)"
    exit 0
fi

unreleased=""
for i in "${!CIRCUITS[@]}"; do
    [[ "${DIGESTS[$i]}" != null ]] || unreleased+="${unreleased:+ }${CIRCUITS[$i]}"
done
[[ -z "$unreleased" ]] || {
    echo "circuits.json pins no release for: $unreleased" >&2
    echo "  build libid-circuits and run: scripts/vendor-circuit-verifiers.sh --local <artifacts>" >&2
    exit 1
}
VERSION="$(jq -r '.version' "$PIN")"
[[ -n "$VERSION" && "$VERSION" != "null" ]] || { echo "no version in $PIN" >&2; exit 1; }
TAG="v$VERSION"
echo "==> libid-circuits $TAG"

WORK="$(mktemp -d)"
STAGE="$(mktemp -d)"
trap 'rm -rf "$WORK" "$STAGE"' EXIT

# The release's own manifest: held to the pin, then used for the per-file
# check inside each tarball.
curl -fsSL -o "$WORK/manifest.json" "$RELEASES/$TAG/manifest.json"
released="$(jq -r '.version' "$WORK/manifest.json")"
[[ "$released" == "$VERSION" ]] ||
    { echo "the $TAG manifest declares version '$released', the pin says $VERSION" >&2; exit 1; }

for i in "${!CIRCUITS[@]}"; do
    circuit="${CIRCUITS[$i]}" contract="${CONTRACTS[$i]}" want="${DIGESTS[$i]}"
    tarball="libid-circuits-$VERSION-$circuit.tar.gz"
    curl -fsSL -o "$WORK/$tarball" "$RELEASES/$TAG/$tarball"

    # The integrity check: the committed digest, nothing downloaded.
    got="$(sha256 "$WORK/$tarball")"
    [[ "$got" == "$want" ]] ||
        { echo "$tarball: sha256 $got, the pin says $want" >&2; exit 1; }
    declared="$(jq -r --arg t "$tarball" '.tarballs[$t].sha256' "$WORK/manifest.json")"
    [[ "$declared" == "$want" ]] ||
        { echo "$tarball: the $TAG manifest declares sha256 '$declared', the pin says $want" >&2; exit 1; }

    mkdir -p "$WORK/$circuit"
    tar xzf "$WORK/$tarball" -C "$WORK/$circuit"
    # Every file the manifest lists is in the tarball at the digest it
    # names; the tarball is trusted, so this catches a release that was
    # assembled wrong, not an attacker.
    while IFS=$'\t' read -r name file_want; do
        [[ -f "$WORK/$circuit/$name" ]] ||
            { echo "$tarball: the manifest lists $name, the tarball lacks it" >&2; exit 1; }
        file_got="$(sha256 "$WORK/$circuit/$name")"
        [[ "$file_got" == "$file_want" ]] ||
            { echo "$tarball: $name sha256 $file_got, the manifest says $file_want" >&2; exit 1; }
    done < <(jq -r --arg t "$tarball" '.tarballs[$t].files | to_entries[] | "\(.key)\t\(.value)"' "$WORK/manifest.json")

    require_table "$WORK/$circuit" "$circuit"
    write_verifier "$WORK/$circuit/$contract.sol" "$contract" \
        "// Vendored from libid-circuits $TAG ($tarball) by scripts/vendor-circuit-verifiers.sh. Do not edit.\n// The pin is $DEST_REL/circuits.json; \`forge fmt\` is the only change to what shipped."
    echo "==> $circuit -> $DEST_REL/$contract.sol"
done

cp "$STAGE"/*.sol "$DEST/"
write_codehashes "libid-circuits $TAG"
