// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by libID-contracts' scripts/regen-identity-handles.py. Do not edit.
// The source of truth is libID-contracts' solidity/contracts/handles/handles.json.

import {HandleNormalizer} from "./HandleNormalizer.sol";

/// @notice Each platform `handles.json` names: its id, its handle rules and
///         its node tags, as the production contracts read them.
///
/// @dev The vector table the languages share is `HandleVectors`, which
///      only tests read.
library HandlePlatforms {
    /// @notice `handles.json` names no such platform.
    error UnknownPlatform(bytes32 platformId);

    /// SHA-256 of the handles.json this file was generated from.
    bytes32 internal constant TABLE_SHA256 = 0xbacafa6023dd82852f753efa04635b36899b881f5d37fe15260e7dd532272560;

    /// keccak256(bytes("x"))
    bytes32 internal constant PLATFORM_X = keccak256(bytes("x"));
    /// keccak256(bytes("github"))
    bytes32 internal constant PLATFORM_GITHUB = keccak256(bytes("github"));
    /// keccak256(bytes("google"))
    bytes32 internal constant PLATFORM_GOOGLE = keccak256(bytes("google"));

    /// `libid.x.user-id`: an id node is SHA256 of this, then the id.
    bytes internal constant USER_ID_TAG_X = "libid.x.user-id";
    /// `libid.x.handle`: a handle node is SHA256 of this, then the
    /// normalized handle.
    bytes internal constant HANDLE_TAG_X = "libid.x.handle";
    /// `libid.github.user-id`: an id node is SHA256 of this, then the id.
    bytes internal constant USER_ID_TAG_GITHUB = "libid.github.user-id";
    /// `libid.github.handle`: a handle node is SHA256 of this, then the
    /// normalized handle.
    bytes internal constant HANDLE_TAG_GITHUB = "libid.github.handle";
    /// `libid.google.user-id`: an id node is SHA256 of this, then the id.
    bytes internal constant USER_ID_TAG_GOOGLE = "libid.google.user-id";
    /// `libid.google.handle`: a handle node is SHA256 of this, then the
    /// normalized handle.
    bytes internal constant HANDLE_TAG_GOOGLE = "libid.google.handle";

    /// Whether `handles.json` names this platform.
    function knows(bytes32 platformId) internal pure returns (bool) {
        return platformId == PLATFORM_X || platformId == PLATFORM_GITHUB || platformId == PLATFORM_GOOGLE;
    }

    /// The tag a platform's id nodes are hashed under.
    ///
    /// @dev Reverts on an unknown platform, as `rulesFor` does.
    function userIdTagFor(bytes32 platformId) internal pure returns (bytes memory) {
        if (platformId == PLATFORM_X) return USER_ID_TAG_X;
        if (platformId == PLATFORM_GITHUB) return USER_ID_TAG_GITHUB;
        if (platformId == PLATFORM_GOOGLE) return USER_ID_TAG_GOOGLE;
        revert UnknownPlatform(platformId);
    }

    /// The tag a platform's handle nodes are hashed under.
    ///
    /// @dev Reverts on an unknown platform, as `rulesFor` does.
    function handleTagFor(bytes32 platformId) internal pure returns (bytes memory) {
        if (platformId == PLATFORM_X) return HANDLE_TAG_X;
        if (platformId == PLATFORM_GITHUB) return HANDLE_TAG_GITHUB;
        if (platformId == PLATFORM_GOOGLE) return HANDLE_TAG_GOOGLE;
        revert UnknownPlatform(platformId);
    }

    /// The normalizer rules for a platform, as `handles.json` states
    /// them.
    ///
    /// @dev Generated so a deploy, a test and a consumer cannot each
    ///      keep their own copy. Reverts on an unknown platform rather
    ///      than returning a permissive default, because a wrong rule
    ///      set writes wrong nodes.
    function rulesFor(bytes32 platformId) internal pure returns (HandleNormalizer.Rules memory rules) {
        (rules,) = _handleKeys(platformId);
    }

    /// The handle typed text names on a platform, normalized with its
    /// rules, and the node it is bound under, hashed under its tag.
    ///
    /// @dev Reverts `UnusableHandle` for text the rules refuse, and
    ///      `UnknownPlatform`.
    function handleNodeOf(bytes32 platformId, string memory raw)
        internal
        pure
        returns (string memory normalized, bytes32 handleNode)
    {
        (HandleNormalizer.Rules memory rules, bytes memory tag) = _handleKeys(platformId);
        return HandleNormalizer.nodeOf(raw, rules, tag);
    }

    /// `handleNodeOf`, reporting what the rules refuse instead of reverting.
    ///
    /// @dev Reverts `UnknownPlatform`.
    function tryHandleNodeOf(bytes32 platformId, string memory raw)
        internal
        pure
        returns (HandleNormalizer.Problem problem, bytes32 handleNode)
    {
        (HandleNormalizer.Rules memory rules, bytes memory tag) = _handleKeys(platformId);
        return HandleNormalizer.tryNodeOf(raw, rules, tag);
    }

    function _handleKeys(bytes32 platformId)
        private
        pure
        returns (HandleNormalizer.Rules memory rules, bytes memory tag)
    {
        if (platformId == PLATFORM_X) {
            rules = HandleNormalizer.Rules({maxLength: 15, isEmail: false, allowUnderscore: true, allowHyphen: false});
            return (rules, HANDLE_TAG_X);
        }
        if (platformId == PLATFORM_GITHUB) {
            rules = HandleNormalizer.Rules({maxLength: 39, isEmail: false, allowUnderscore: false, allowHyphen: true});
            return (rules, HANDLE_TAG_GITHUB);
        }
        if (platformId == PLATFORM_GOOGLE) {
            rules = HandleNormalizer.Rules({maxLength: 62, isEmail: true, allowUnderscore: false, allowHyphen: false});
            return (rules, HANDLE_TAG_GOOGLE);
        }
        revert UnknownPlatform(platformId);
    }
}
