// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by scripts/regen-identity-handles.py. Do not edit.
// The source of truth is solidity/contracts/handles/handles.json.

import {HandleNormalizer} from "./HandleNormalizer.sol";

/// @notice Platform ids and the shared handle vector table.
///
/// @dev The vectors are here rather than in the test file because Rust and
///      TypeScript run the same table. A normalizer that disagrees with
///      another language fails a test instead of writing a different node.
library HandleVectors {
    /// SHA-256 of the handles.json this file was generated from.
    bytes32 internal constant TABLE_SHA256 = 0xea81ef6430403fa5ac1be4382814df826164217f020cf770f4c1b780db80a1a9;

    /// keccak256(bytes("x"))
    bytes32 internal constant PLATFORM_X = keccak256(bytes("x"));
    /// keccak256(bytes("github"))
    bytes32 internal constant PLATFORM_GITHUB = keccak256(bytes("github"));
    /// keccak256(bytes("google"))
    bytes32 internal constant PLATFORM_GOOGLE = keccak256(bytes("google"));

    uint256 internal constant MAX_LENGTH_X = 15;
    uint256 internal constant MAX_LENGTH_GITHUB = 39;
    uint256 internal constant MAX_LENGTH_GOOGLE = 62;

    /// `libid.x.user-id`: an id node is SHA256 of this, then the id.
    bytes internal constant USER_ID_TAG_X = "libid.x.user-id";
    /// `libid.x.handle`: a handle node is SHA256 of this, then the
    /// normalized handle.
    bytes internal constant HANDLE_TAG_X = "libid.x.handle";
    /// `libid.github.user-id`: an id node is SHA256 of this, then the id.
    bytes internal constant USER_ID_TAG_GITHUB = "libid.github.user-id";
    /// `libid.github.handle`: a handle node is SHA256 of this, then the
    /// normalized handle.
    bytes internal constant HANDLE_TAG_GITHUB = "libid.github.handle";
    /// `libid.google.user-id`: an id node is SHA256 of this, then the id.
    bytes internal constant USER_ID_TAG_GOOGLE = "libid.google.user-id";
    /// `libid.google.handle`: a handle node is SHA256 of this, then the
    /// normalized handle.
    bytes internal constant HANDLE_TAG_GOOGLE = "libid.google.handle";

    /// Whether `handles.json` names this platform.
    function knows(bytes32 platformId) internal pure returns (bool) {
        return platformId == PLATFORM_X || platformId == PLATFORM_GITHUB || platformId == PLATFORM_GOOGLE;
    }

    /// The tag a platform's id nodes are hashed under.
    ///
    /// @dev Reverts on an unknown platform, as `rulesFor` does.
    function userIdTagFor(bytes32 platformId) internal pure returns (bytes memory) {
        if (platformId == PLATFORM_X) return USER_ID_TAG_X;
        if (platformId == PLATFORM_GITHUB) return USER_ID_TAG_GITHUB;
        if (platformId == PLATFORM_GOOGLE) return USER_ID_TAG_GOOGLE;
        revert("unknown platform");
    }

    /// The tag a platform's handle nodes are hashed under.
    ///
    /// @dev Reverts on an unknown platform, as `rulesFor` does.
    function handleTagFor(bytes32 platformId) internal pure returns (bytes memory) {
        if (platformId == PLATFORM_X) return HANDLE_TAG_X;
        if (platformId == PLATFORM_GITHUB) return HANDLE_TAG_GITHUB;
        if (platformId == PLATFORM_GOOGLE) return HANDLE_TAG_GOOGLE;
        revert("unknown platform");
    }

    /// The normalizer rules for a platform, as `handles.json` states
    /// them.
    ///
    /// @dev Generated so a deploy, a test and a consumer cannot each
    ///      keep their own copy. Reverts on an unknown platform rather
    ///      than returning a permissive default, because a wrong rule
    ///      set writes wrong nodes.
    function rulesFor(bytes32 platformId) internal pure returns (HandleNormalizer.Rules memory) {
        if (platformId == PLATFORM_X) {
            return HandleNormalizer.Rules({maxLength: 15, isEmail: false, allowUnderscore: true, allowHyphen: false});
        }
        if (platformId == PLATFORM_GITHUB) {
            return HandleNormalizer.Rules({maxLength: 39, isEmail: false, allowUnderscore: false, allowHyphen: true});
        }
        if (platformId == PLATFORM_GOOGLE) {
            return HandleNormalizer.Rules({maxLength: 62, isEmail: true, allowUnderscore: false, allowHyphen: false});
        }
        revert("unknown platform");
    }

    /// One case from the shared table.
    struct Vector {
        string platform;
        string input;
        string output;
        bool accepted;
        uint8 errorKind;
        bytes32 handleNode;
    }

    uint8 internal constant ERROR_EMPTY = 0;
    uint8 internal constant ERROR_TOOLONG = 1;
    uint8 internal constant ERROR_BADCHARACTER = 2;
    uint8 internal constant ERROR_BADSHAPE = 3;

    uint256 internal constant COUNT = 46;

    function all() internal pure returns (Vector[] memory v) {
        v = new Vector[](46);
        v[0] = Vector({
            platform: "x", input: " @Alice_1 ", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[1] = Vector({
            platform: "x",
            input: "Alice_1",
            output: "alice_1",
            accepted: true,
            errorKind: 0,
            handleNode: 0xe09c4f5bfbbc723bc35701ea9d718a1c5edb29b1ed5bb0cb0fabb3c43d8136af
        });
        v[2] = Vector({
            platform: "x",
            input: "alice",
            output: "alice",
            accepted: true,
            errorKind: 0,
            handleNode: 0x0bed64615b5776d2567a82467d7be0e266e02803910d694a72703ee2a4cc911a
        });
        v[3] = Vector({platform: "x", input: "@a", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)});
        v[4] = Vector({
            platform: "x",
            input: "A1_b2",
            output: "a1_b2",
            accepted: true,
            errorKind: 0,
            handleNode: 0x55be0847f475409cb1da1d008804b966de05bb088d2469129c142faf2ec4a678
        });
        v[5] = Vector({
            platform: "x",
            input: "a12345678901234",
            output: "a12345678901234",
            accepted: true,
            errorKind: 0,
            handleNode: 0xbd3a96fb00ea79bdb486cbaa43914f8c110c8585d419fc02e5b1536c7617af58
        });
        v[6] = Vector({
            platform: "x", input: "a123456789012345", output: "", accepted: false, errorKind: 1, handleNode: bytes32(0)
        });
        v[7] = Vector({platform: "x", input: "", output: "", accepted: false, errorKind: 0, handleNode: bytes32(0)});
        v[8] = Vector({platform: "x", input: "   ", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)});
        v[9] = Vector({platform: "x", input: "@", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)});
        v[10] = Vector({
            platform: "x", input: "@@alice", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[11] = Vector({
            platform: "x", input: "alice-1", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[12] =
            Vector({platform: "x", input: "ali ce", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)});
        v[13] = Vector({
            platform: "x", input: "ali\tce", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[14] = Vector({
            platform: "x", input: "ali\nce", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[15] = Vector({
            platform: "x", input: "alic\xc3\xa9", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[16] = Vector({
            platform: "x", input: "\talice", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[17] = Vector({
            platform: "x", input: "alice\t", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[18] = Vector({
            platform: "x", input: "\nalice", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[19] = Vector({
            platform: "x", input: " @ alice ", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[20] = Vector({
            platform: "github",
            input: "OctoCat",
            output: "octocat",
            accepted: true,
            errorKind: 0,
            handleNode: 0x381fb9d7d3b01214e58b94202ea10f78e169adef68bcc20d40c130deca6dfe74
        });
        v[21] = Vector({
            platform: "github", input: "@Octo-Cat", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[22] = Vector({
            platform: "github",
            input: "octocat",
            output: "octocat",
            accepted: true,
            errorKind: 0,
            handleNode: 0x381fb9d7d3b01214e58b94202ea10f78e169adef68bcc20d40c130deca6dfe74
        });
        v[23] = Vector({
            platform: "github", input: " OctoCat ", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[24] = Vector({
            platform: "github",
            input: "a",
            output: "a",
            accepted: true,
            errorKind: 0,
            handleNode: 0x823c23491391b659703362484a08cfbcc8cede4ea3b5ba1753c3df7756799c70
        });
        v[25] = Vector({
            platform: "github",
            input: "o-c",
            output: "o-c",
            accepted: true,
            errorKind: 0,
            handleNode: 0xaa580baff71ac37d38e08b9b7b0dd7516ec01608457fbbee7f445a0b8f7d9fc5
        });
        v[26] = Vector({
            platform: "github", input: "-octocat", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)
        });
        v[27] = Vector({
            platform: "github", input: "octocat-", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)
        });
        v[28] = Vector({
            platform: "github", input: "octo--cat", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)
        });
        v[29] = Vector({
            platform: "github", input: "octo_cat", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[30] =
            Vector({platform: "github", input: "-", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)});
        v[31] =
            Vector({platform: "github", input: "", output: "", accepted: false, errorKind: 0, handleNode: bytes32(0)});
        v[32] = Vector({
            platform: "github",
            input: "abcdefghijabcdefghijabcdefghijabcdefghi",
            output: "abcdefghijabcdefghijabcdefghijabcdefghi",
            accepted: true,
            errorKind: 0,
            handleNode: 0x3f7bdb081795e2934e1e949f1933b8df950a6e6026dbc70060fc3a79b693a058
        });
        v[33] = Vector({
            platform: "github",
            input: "abcdefghijabcdefghijabcdefghijabcdefghij",
            output: "",
            accepted: false,
            errorKind: 1,
            handleNode: bytes32(0)
        });
        v[34] = Vector({
            platform: "github", input: "\n", output: "", accepted: false, errorKind: 2, handleNode: bytes32(0)
        });
        v[35] = Vector({
            platform: "google",
            input: "A.B+tag@Example.COM",
            output: "a.b+tag@example.com",
            accepted: true,
            errorKind: 0,
            handleNode: 0x40169b5cc6400158aeef2a13b73a14fc36e5e1df8595572b8fe282a269f26dd4
        });
        v[36] = Vector({
            platform: "google",
            input: "alice@example.com",
            output: "alice@example.com",
            accepted: true,
            errorKind: 0,
            handleNode: 0x41c79cba63d5bd4735ca51af1af31702918f326eb6fc1afd853d675fee3a59cc
        });
        v[37] = Vector({
            platform: "google",
            input: " Alice@Example.com ",
            output: "",
            accepted: false,
            errorKind: 2,
            handleNode: bytes32(0)
        });
        v[38] = Vector({
            platform: "google",
            input: "@Alice@example.com",
            output: "",
            accepted: false,
            errorKind: 3,
            handleNode: bytes32(0)
        });
        v[39] = Vector({
            platform: "google", input: "alice", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)
        });
        v[40] = Vector({
            platform: "google", input: "@example.com", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)
        });
        v[41] = Vector({
            platform: "google", input: "alice@", output: "", accepted: false, errorKind: 3, handleNode: bytes32(0)
        });
        v[42] =
            Vector({platform: "google", input: "", output: "", accepted: false, errorKind: 0, handleNode: bytes32(0)});
        v[43] = Vector({
            platform: "google",
            input: "ali ce@example.com",
            output: "",
            accepted: false,
            errorKind: 2,
            handleNode: bytes32(0)
        });
        v[44] = Vector({
            platform: "google",
            input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com",
            output: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij@example.com",
            accepted: true,
            errorKind: 0,
            handleNode: 0x3dc67054a8f794285dc9496fd7c2442ef34401b5e3f6a49e7d3fd9cc6a917e97
        });
        v[45] = Vector({
            platform: "google",
            input: "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijk@example.com",
            output: "",
            accepted: false,
            errorKind: 1,
            handleNode: bytes32(0)
        });
    }
}
